### ISSUE TITLE
Return value of declared user function is casted which leads to loose of a precision

### ISSUE THREAD

**Issue by krystian-wojtas** [marcoschwartz/aREST#100]
Hi Marco,

Thanks for this library :)

I found that return int value of user defined function is casted to uint8_t which leads to lose of a precision. Then result is incorrect.

My user function is declared as:
```
  rest.function("temp",getTemperature);
```
with definition
```
int getTemperature(String _)
{
    DS18B20.requestTemperatures(); 
    float temp = DS18B20.getTempCByIndex(0);
    int base = floor(temp + 0.5);
    int rest = (temp - base) * 100;
    
    return base * 100 + rest;
}
```

However lines 1029-1024 in library file are casting passed result
```
  // Function selected
  if (command == 'f') {

    // Execute function
    uint8_t result = functions[value](arguments);
```

What do you thing about avoiding this cast?

In case of my function definition, the return type of float would be more suitable. But as I understand that your intention was to support hardware even without floating point unit, then maybe the most generic way to handle user functions would be a prototype like
```
String (*f)(String)
```
Then user function has to make a proper conversion or rely on automatic conversion in cpp. What do you think?

Cheers,
Krystian

**Comment by marcoschwartz** [comment]
Hello Krystian! Basically the primary goal of the data returned by the function is to return some 'status' about the execution of the function, not actually data. In your case, I'd simply write down the measurement result in a float variable, and then expose this variable to aREST :) Does that answer your question?
