### ISSUE TITLE
i have a trouble for load cloud access by ESP8266

### ISSUE THREAD

**Issue by Johnuino** [marcoschwartz/aREST#103]
I have a problem when I check the draft, does not allow me to continue, thank you for your valuable help, I'm working with a chip esp8266-12e.

Arduino:1.6.5 (Windows 7), Placa:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200"

Utilizando biblioteca ESP8266WiFi en carpeta: C:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi 

Utilizando biblioteca PubSubClient en carpeta: D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\pubsubclient-master 

Utilizando biblioteca aREST en carpeta: D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST 

C:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -IC:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266 -IC:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\cores\esp8266 -IC:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\variants\nodemcu -IC:\Users\jacevedo\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi\src -ID:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\pubsubclient-master\src -ID:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST C:\Users\jacevedo\AppData\Local\Temp\build8813185254727650732.tmp\cloudAccessESP8266Swart.cpp -o C:\Users\jacevedo\AppData\Local\Temp\build8813185254727650732.tmp\cloudAccessESP8266Swart.cpp.o 

cloudAccessESP8266Swart.ino:21:19: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
cloudAccessESP8266Swart.ino: In function 'void setup()':
cloudAccessESP8266Swart.ino:45:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
cloudAccessESP8266Swart.ino:46:37: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
cloudAccessESP8266Swart.ino:50:26: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
cloudAccessESP8266Swart.ino: In function 'void loop()':
cloudAccessESP8266Swart.ino:69:21: error: no matching function for call to 'aREST::handle(PubSubClient&)'
cloudAccessESP8266Swart.ino:69:21: note: candidates are:
In file included from cloudAccessESP8266Swart.ino:11:0:
D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST/aREST.h:250:6: note: void aREST::handle(WiFiClient&)
 void handle(WiFiClient& client){
      ^
D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST/aREST.h:250:6: note:   no known conversion for argument 1 from 'PubSubClient' to 'WiFiClient&'
D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST/aREST.h:340:6: note: void aREST::handle(char*)
 void handle(char * string) {
      ^
D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\aREST/aREST.h:340:6: note:   no known conversion for argument 1 from 'PubSubClient' to 'char*'
Multiple libraries were found for "PubSubClient.h"

 Used: D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\pubsubclient-master

 Not used: C:\Program Files (x86)\Arduino\libraries\pubsubclient-master

 Not used: D:\Harold\Estudio\Arduino\Programas ESP8266-12E\libraries\PubSubClient

no matching function for call to 'aREST::handle(PubSubClient&)'

**Comment by marcoschwartz** [comment]
I think the problem is here: Multiple libraries were found for "PubSubClient.h"
