### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by wblaircox** [marcoschwartz/aREST#107]
Hi Marco, 

Sorry to dig this one up. But while I see the header information has been added, I'm getting the same access error;

XMLHttpRequest cannot load https://cloud.arest.io/xxxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access.

I'm creating a test app, so I just want to use the JSON provided without getting into the weeds. Have an fast and easy fix for this? (I'm configuring my own MQQT server, but that will come later)

Cheers,
Blair

![image](https://cloud.githubusercontent.com/assets/12896777/14892927/99f07de2-0d43-11e6-92b7-223ddb8216b9.png)

**Comment by marcoschwartz** [comment]
Hi, not a problem! You mean you would like those headers to be returned from the aREST cloud server as well?

Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS

**Comment by wblaircox** [comment]
Ideally, yes. Just for testing. But understood if that is a no no.

**Comment by wblaircox** [comment]
Is there a place I put this? 

Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS

**Comment by marcoschwartz** [comment]
I think it would be easy for me to insert it on the cloud server side. I'll test if and if it doesn't break anything, I'll push the change to the live server :)

**Comment by wblaircox** [comment]
Awesome! Thanks Marco! :)

**Comment by wblaircox** [comment]
But maybe I'm doing this incorrectly - because you provide the json...have to be able to consume it somehow? I'm doing it the way I always do it jQuery.getJSON()  Is there another way I can have my little test app grab the json without trigger the cross domain issue?

**Comment by marcoschwartz** [comment]
If you are trying to access the API on the client side, what you need is to use this:

http://api.jquery.com/jquery.ajax/

With the crossDomain option set to true. Maybe this would work immediately for you :)

**Comment by wblaircox** [comment]
Great, will take a look, thanks. Silly IoT newbie question... How did you
envision the cloud.arest.io json output being used? (I bought your boo,k
maybe I'm missing/not seeing this part?)

Cheers,
Blair

**Comment by marcoschwartz** [comment]
Well that's entirely up to you :) You can use it as you wish in any app you are building, just as feedback from the server or for example to log data in your own database.

**Comment by wblaircox** [comment]
Thanks! I ended up going the route in your book with my own aREST/MQTT server om DigitalOcean - Some mistake made for an interesting learning curve.
