### ISSUE TITLE
Tutorial 3.6.3 - Very last step not working

### ISSUE THREAD

**Issue by wblaircox** [marcoschwartz/aREST#110]
Followed your tutorial - Connect a Device to Your Cloud Server (3.6.3). Few bumps along the way, but got all the way to the end. I'm using the ESP8266 and had it working with cloud.arest.io. I made the require IP change noted on page 168. The DigitalOcean server appears to be working properly (as far as I can tell), waiting for a connection.

However while looking at the Arduino 1.6.8 console, I get the following;

Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

I did make one additional change in the mup.json. I renamed the Application to something other than arest. 
// Application name (No spaces)
"appName": "arest",

Any thoughts on where to check?

**Comment by kiralikbeyin** [comment]
Try to make a test with examples of https://github.com/knolleary/pubsubclient

Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

This error is related with pubsubclient.h

**Comment by wblaircox** [comment]
Okay thanks - any ideas where / how? Since I'm following the book and using the stock elements... hmmm a version issue? Just seems like maybe there is a step missing in the book maybe? It works with cloud.arest.io, and even works/connects to the couple other open MQTT brokers out there. 

* I'm using the Arduino Windows app to load the sketch on the ESP8266 board. The required libraries are loaded using that tool. If there is a problem with  PubSubSlient.h, it's a problem for everyone.

**Comment by kiralikbeyin** [comment]
Modify aREST.h at the end

`  const char* mqtt_server = "XXX.XXX.XXX.XXX"; //your server ip
`

You can check if your server's mqtt is working with pubsubclient.h examples

**Comment by wblaircox** [comment]
I'll try it and let you know! Thanks! Is this because I used the library loader in the Arduino Genuino tool and not manually installed it??

**Comment by marcoschwartz** [comment]
The right way without modifying the library is to do:

aREST rest = aREST(client, "XXX.XXX.XXX.XXX");

Let me know if that works :)

**Comment by wblaircox** [comment]
Yup! Did that. I'll give it another go! :)

**Comment by wblaircox** [comment]
I redid the entire tutorial per the book. Rather than using mup, mupx is required. But in the end, the results are the same as the first attempt. 

The aREST cloud won't meet my needs. Switching to a full MQTT server - took 5 minutes to get working.

**Comment by marcoschwartz** [comment]
The deployment of the aREST app now works with both mup & mupx - but as mupx is the way to go in the future I updated the book with mupx :)
