### ISSUE TITLE
cloud-device connect

### ISSUE THREAD

**Issue by kiralikbeyin** [marcoschwartz/aREST#111]
I was running cloud arest from book in my local server a few weeks ago but now esp8266 publishes to mqtt but meteor doesn’t log any new connected device.

<img width="640" alt="aaa" src="https://cloud.githubusercontent.com/assets/10079333/14965898/8803c166-10b8-11e6-92d8-02d914ad112d.png">

**Comment by marcoschwartz** [comment]
I answered to your email, so closing this :)

**Comment by kiralikbeyin** [comment]
How do you run arest in local?

I want to modify ui but can’t run server in local..
