### ISSUE TITLE
Question: How to add more device to a HTML page?

### ISSUE THREAD

**Issue by klerone** [marcoschwartz/aREST#112]
Hi Marco.

Thank you for your great job.
Currently I'm working to get the reading of 2 ESP8266 in a html page, I saw the function Device, and I try to make it work but i get nothing.

I did it:
- change device id in the sketch for each ESP.
- in the html file i added an input to type the IP of the second device (Device_2)
- in the aREST.js file i added a new Function called Device_2.
- in the script.js  added the function to call the variables from Device_2.

At this point a get nothing form the ESP. I will appreciate your help.

**Comment by marcoschwartz** [comment]
Hi Klerone, thank you! Can you please open this issue on the aREST.js repository? This one is only about the Arduino library. Thanks!

**Comment by klerone** [comment]
Sure, thank you.
I found how to do, is easy as your example say. Just i messed up my code. I will delete it.
