### ISSUE TITLE
 Serial.print("Memory loss before reset:");

### ISSUE THREAD

**Issue by matthewbaggett** [marcoschwartz/aREST#116]
There are a few Serial.print() lines in the source affecting the ESP8266.

> Memory loss before reset:184
> Memory loss after reset:0
> Memory free:40768

I also need to do a Serial.print("") immediately after calling rest.handle(client), otherwise I get a crash.

**Comment by marcoschwartz** [comment]
Are those messages also appearing when you have the DEBUG_MODE set to 0?

**Comment by peeter81** [comment]
I have a same problem, Serial Monitor shows:

Memory loss before reset:184
Memory loss after reset:0
Memory free:37784

Memory loss before reset:0
Memory loss after reset:0
Memory free:37784

Memory loss before reset:0
Memory loss after reset:0
Memory free:37784

Memory loss before reset:0
Memory loss after reset:0
Memory free:37784

Memory loss before reset:0
Memory loss after reset:0
Memory free:37784

and so on...

Is this problem for ESP12-E (NodeMCU 1.0)? 
Is it going to crash finally after some time working?

**Comment by marcoschwartz** [comment]
This is now fixed in the latest version of the library, it will only appear if you enable the debug mode :)

**Comment by peeter81** [comment]
To check debug mode is disabled (not enabled) should i open my aREST.h library on harddrive folder 
(same as here https://github.com/marcoschwartz/aREST/blob/master/aREST.h) and check 
if debug mode is set to 0 ?

like here
// Debug mode
#ifndef DEBUG_MODE
#define DEBUG_MODE 0
#endif

?

**Comment by marcoschwartz** [comment]
You don't actually need to go into the library file, just put:

#define DEBUG_MODE 0

At the start of your sketch if you want to be sure :)
