### ISSUE TITLE
call Arest from python script 

### ISSUE THREAD

**Issue by OdysLam** [marcoschwartz/aREST#117]
Hey,

I am trying to control my 
Arest device(esp8266) through REST calls from a custom python script (using the requests library).

As I am new to the REST sport, I haven't been able to figure out what kind of REST calls each arest command is. Since they are meant to be entered in the web browser I am guessing that are are all GET, but I can't find anywhere where it is beig said explicitly .

Thank you in advance and cheers for this awesome library.

**Comment by OdysLam** [comment]
Although it would definitely be useful, using the requests library is pretty straightforward
`resp = requests.get(self.address + "/" + function + "/" + pin)
answer = resp.json()`

The second command is only needed if I want to do something with the response,otherway just the first line will trigger the needed action.

Maybe it would be better to write a small walkthrough(something I could even do when I get my esp and have a chance to test my code) and focus on the arest library itself (like providing more API calls) or whatever you are cooking this time around .

**Comment by nbarry101** [comment]
Give this a go

```
import urllib2
import json

base_url = 'http://192.168.1.44:81'
pin = 2

url_digital = base_url + '/digital/' + str(pin)

response_json = json.load(urllib2.urlopen(url_digital))

url_digital_return_value = response_json['return_value']
url_digital_name = response_json['name']

print response_json
print 'name: ' + url_digital_name
print 'return_value: ' + str(url_digital_return_value)
```
