### ISSUE TITLE
Serial Mode not working ?

### ISSUE THREAD

**Issue by Gamezpedia** [marcoschwartz/aREST#118]
Hi,

i just checked the serial example and just compile it on the Arduino Uno, now what is happening :

**1 -** When you open up the Serial monitor 
**2 -** It will show this : 

> {"variables": {"temperature": 24, "humidity": 40}, "id": "2", "name": "serial", "hardware": "arduino", "connected": true}

which prints only once then as the **link** [https://arest.io/serial/](https://arest.io/serial/) say
**/mode/13/o
/digital/13/1**

**3 -** I just copy and paste any one of them in the Serial Monitor and send it to the the board.
**4 -** what happen is the same above response is keep repeating . check attached image file : 

![image](https://cloud.githubusercontent.com/assets/1169093/16716765/87d728f2-471f-11e6-9ad7-1f3e22562cb8.png)

**5 -** I noticed one thing too that LED on the board is constantly remains ON after pushing the code to the board.
- I am trying it for the first time i have ordered the wifi shields to build something, and i wanted to test this out with that too , but it seems i am stuck in here with the serial thing , wifi is another titanic story :S kindly someone please help . thanks

**Comment by marcoschwartz** [comment]
Hello, I just tested the Serial sketch again on an Arduino Uno, works fine on my side :) Make sure you have the latest version of the Arduino IDE & the library and try again. Also make sure nothing else is sending data to this Serial port, this could be the reason of all those answers from the  board.

**Comment by masoud1989** [comment]
Actually i have this problem too 
when i use this command   /mode/13/o
it never set pin 13 to output and i will see this statement
{"message": "Pin D13"id": "2", "name": "serial", "hardware": "arduino", "connected": true}

![image](https://cloud.githubusercontent.com/assets/22577385/21744437/e3f2c062-d52a-11e6-8380-0c26dc7f3712.png)

**Comment by marcoschwartz** [comment]
Hi, can you let me know which hardware you are using?

**Comment by masoud1989** [comment]
My board is Arduino UNO R3
my chip is : Atmega328

**Comment by masoud1989** [comment]
the picture of my board is:
![photo_2017-01-09_21-23-32](https://cloud.githubusercontent.com/assets/22577385/21776888/e9485d78-d6b1-11e6-923a-cd6b2a949ebe.jpg)
![photo_2017-01-09_21-23-29](https://cloud.githubusercontent.com/assets/22577385/21776893/ef29dc30-d6b1-11e6-9909-4d86e3964188.jpg)

**Comment by masoud1989** [comment]
i am using windows 8.1 my arduino IDE is 1.8.0

**Comment by masoud1989** [comment]
please help me F1

**Comment by marcoschwartz** [comment]
Ok, found the problem from your screenshot :) Make sure to put "Both NL & CR" in the Serial monitor and it will work :)
