### ISSUE TITLE
Question: Not able to send multiple sequential request to web server

### ISSUE THREAD

**Issue by shaikhmshariq** [marcoschwartz/aREST#119]
Hi 
I am stuck with Arduino code where I need to receive multiple sequential request from client and update value in Arduino board. I am using Ethernet board with Arduino and aRest library to expose Arduino board with RESTFul services.

Please check below code and let me know what should I modify or edit to achieve below requirements (note that I have commented watchdog related code),

[Motor Sample](https://gist.github.com/shaikhmshariq/36264bf20f24faf078c4155542fc6836)

I need to receive multiple (sequential) requests from client through EthernetClient and update Motor speed based on received input. When I run the code below,

- With watchdog - it resets the board and because of it motor shuts down after 4 seconds that is not what I want.

- Without watchdog- it doesn't receive second request at all, which means server doesn't respond at all after serving first request for which I receive instant response from server.

**Comment by marcoschwartz** [comment]
Hello, for personalised help on your code that's not directly a problem with aREST please write to me directly at contact@arest.io, thanks!
