### ISSUE TITLE
Device not found in cloud since server update 2.3

### ISSUE THREAD

**Issue by saliehendricks** [marcoschwartz/aREST#120]
Since the update my devices are not connecting to the server. A few reboots and still no connection. 

Do we have to update the client code? 
....
Checked the last commit, the mqtt server is now changed to "45.55.196.201" and the way the device id works is different? 

@marcoschwartz could you advise on whether we can still set our own id's or whether we should use the auto generated one?

**Comment by marcoschwartz** [comment]
Hello, indeed you need to update the client in order to continue using aREST. Sorry about the problems it can cause, but it was a really needed change for the future of aREST.

For now you still need to set your own ID in the code, it doesn't (yet) generate an ID for you.
