### ISSUE TITLE
Set input from inside the sketch

### ISSUE THREAD

**Issue by OdysLam** [marcoschwartz/aREST#122]
Hey,

Can I set I/O from inside the sketch so in case i get a random reboot, I can be sure that esp will be set-itself correctly?

Also is there any documentation of the native C functions that the library includes?

Awesome lib,keep the magic going!

**Comment by saliehendricks** [comment]
Yes, you can. Nothing prevents you from setting the pinMode. I normally do that in the setup()

````c++
 for (int i = 0; i < relayCount; i++)
  {
     pinMode(relayPins[i],OUTPUT);
     digitalWrite(relayPins[i],HIGH);
  }
````

**Comment by marcoschwartz** [comment]
Hey, thanks :) Indeed nothing prevents you to call the usual Arduino function inside the sketch.

**Comment by OdysLam** [comment]
Well Initially I thought that I had to use a aREST specific function, but in reality, when I do the GET request to set a gpio as I/O, in reality I call the function pinMode(PIN,OUTPUT) via aREST, right?

**Comment by marcoschwartz** [comment]
Exactly :) aREST just calls the usual Arduino functions via HTTP requests :)

**Comment by OdysLam** [comment]
Awesome, thanks for the help! :)
