### ISSUE TITLE
HTTP response timeout

### ISSUE THREAD

**Issue by delwinbest** [marcoschwartz/aREST#123]
Howdy,

I found, after much debugging and digging through the code, that when using the examples (specifically ESP8266_softAP) if I run multiple commands in sequence (set pin mode then toggle HIGH/LOW), the browser would timeout and not get a response. 

The reason for this was that in this piece of code:

```
void loop() {
  // Handle REST calls
  WiFiClient client = server.available();
  if (!client) {
    return;
  }
  while(!client.available()){
    delay(1);
   }
  rest.handle(client);
}
```

The 'client = server.available()' is true and your device gets stuck in the 'while(!client.available())' loop. Almost like a debounce if that makes sense (I did not debug the http headers to understand why client was available after rest.handle. 

Generally it's not a good idea to have a infinite while as it makes recovery difficult. 

I would suggest using something like this:

```
void loop(){
  // Handle aREST calls
  WiFiClient client = server.available();
  if (!client) {
    return;
   }
   Serial.println("Client Connected. Waiting for Data:");

  while (client.connected()) {
   if (client.available()) {
      rest.handle(client);
      client.stop();
    } // if (client.available())
  } // while (client.connected())
} // void loop()
```

Works like a charm on my side and found it to be a lot more responsive.

**Comment by kubamolski** [comment]
Hi, 
after hours of debugging and looking for 'what is wrong with my code' I get to the same place...
My prototype is working in AP + (if configured - in runtime) STA mode. The problem occurred when WiFi for STA mode was not available or wrongly configured - communication on AP channel stuck (cause of infinitive loop). Proposed "solution" solved the problem of stacking/hanging communication on AP channel.
Best regards,
Kuba

**Comment by marcoschwartz** [comment]
Hey,

Marking this as a feature request as it seems to indeed solve the issue in soft AP mode. I'll integrate the changes soon to the examples.
