### ISSUE TITLE
Esp12 crashes with arest sketch

### ISSUE THREAD

**Issue by OdysLam** [marcoschwartz/aREST#125]
Whenever i run this sketch, it runs ok for a couple of min and then it crashes, I tried other  example scripts(even complicated ones like arduinoOTA) but they don't seem to crash.

What i get on serial is at 75000 baud(I get the normal messages at 115200) : 
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
��������U�����ZJ��jZjZQ����V�J��QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��P����ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�QU��PԵ��ZJV�������I(+ZQ�
 ets Jan  8 2013,rst cause:6, boot mode:(3,6)

ets_main.c 

My code is bellow:
# include <ESP8266WiFi.h>
# include <ESP8266mDNS.h>
# include <WiFiUdp.h>
# include <ArduinoOTA.h>
# include <aREST.h>
# define LISTEN_PORT      80
# define PC_GPIO    5
# define RELAY_1    14
# define RELAY_2    16
# define RELAY_3    12
# define RELAY_4    13

aREST rest = aREST();
const char\* ssid = "12344";
const char\*  password = "213455";
IPAddress ip(192, 168, 1, 30); //Node static IP
IPAddress gateway(192, 168, 1, 1);
IPAddress subnet(255, 255, 255, 0);

WiFiServer server(LISTEN_PORT);

int turnOnPc(String dmy);

void setup() {
  Serial.begin(115200);
  Serial.println("Booting");
  WiFi.begin(ssid, password);
  WiFi.config(ip, gateway, subnet);
  rest.set_id("1");
  rest.set_name("glados_esp");
  rest.function("pc_on", turnOnPc);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  server.begin();
  Serial.println("WiFi connected");

  pinMode(PC_GPIO, OUTPUT);
  digitalWrite(PC_GPIO, LOW);
  pinMode(RELAY_1, OUTPUT);
  digitalWrite(RELAY_1, LOW);
  pinMode(RELAY_2, OUTPUT);
  digitalWrite(RELAY_2, LOW);
  pinMode(RELAY_3, OUTPUT);
  digitalWrite(RELAY_3, LOW);
  pinMode(RELAY_4, OUTPUT);
  digitalWrite(RELAY_4, LOW);

  Serial.println("outputs have been set");
}
void loop() {
   WiFiClient client = server.available();
  if (!client) {
    return;
   }
   Serial.println("Client Connected. Waiting for Data:");

  while (client.connected()) {
   if (client.available()) {
      rest.handle(client);
      client.stop();
    } // if (client.available())
  } // while (client.connected()) // void loop()

}
int turnOnPc(String dmy) {
  digitalWrite(PC_GPIO, HIGH);
  delay(500);
  digitalWrite(PC_GPIO, LOW);
  return 1;
}

Any ideas?

**Comment by marcoschwartz** [comment]
Hello, which board are you using exactly ? I have no problems here with the NodeMCU board & the Wemos Mini R2

**Comment by javigf** [comment]
Hi I am havin issues with WEMOS D1 Mini PRO (16Mb flash), with local and cloud enabled (ver 2.6.0) keeps crashing/hanging. when access local web page. I had to remove aREST from the project. I´ll try to debug deeper but so far... had to remove it. If you have any tip or recommendation, thanks again...

**Comment by marcoschwartz** [comment]
Closing this as it now works on Wemos :)
