### ISSUE TITLE
Does pin-status changes with digitalWrite()?

### ISSUE THREAD

**Issue by julianpomper** [marcoschwartz/aREST#128]
When I change the pin-"status" via digitalWrite() in code, for example to HIGH. Is the status in the json I get from myip/digital/1 updated too? Or only when I change it with the URL?

**Comment by marcoschwartz** [comment]
What is the question exactly related to aREST ?

**Comment by julianpomper** [comment]
Sorry for that! I updated the description

**Comment by marcoschwartz** [comment]
Yes it is, it will be updated in your example :)
