### ISSUE TITLE
arduino & cc3000 arest function call without parameters called twice

### ISSUE THREAD

**Issue by esaheiskanen** [marcoschwartz/aREST#132]
Hi!

Thank you for your great work!

I'm implementin arest servise and i'm using functions to interact. Everything works fine when giving  params but when I try to call arest function without parameters, function is called twice. When I have parameter, function is called once. any ideas why?

Function called once: `http://192.168.100.24/togglepump?params=0`

Function called twice: `http://192.168.100.24/togglepump` or `http://192.168.100.24/togglepump?params=`

**Comment by marcoschwartz** [comment]
Closing this as the CC3000 is not officially supported anymore by aREST.
