### ISSUE TITLE
arduino/genuino 101 support

### ISSUE THREAD

**Issue by gentilmente** [marcoschwartz/aREST#135]
Is there a way to use this board?
https://www.arduino.cc/en/Main/ArduinoBoard101

IDE display this:
`/Arduino/libraries/aREST/examples/Serial/Serial.ino:11:21: fatal error: avr/wdt.h: No such file or directory
 #include <avr/wdt.h>
                     ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino 101.
`
thanks

**Comment by marcoschwartz** [comment]
Should work indeed :) Can you just try by removing/commenting the line #include <avr/wdt.h> ?

**Comment by gentilmente** [comment]
thanks, it worked
