### ISSUE TITLE
Can't view data online

### ISSUE THREAD

**Issue by botletics** [marcoschwartz/aREST#149]
I used aREST before for my first project and it worked great, but for some reason recently it just quit working. The device shows the usual "Attempting MQTT connection...Connected to aREST.io" message but when I go online it spins until it shows the 504 gateway timeout error. However, the aREST status page shows everything is up and running and I don't think I am exceeding the 5 daily devices or 1000 requests per month. Again, everything worked fine before but recently it just stopped working (like the past week).

Any help would be much appreciated. Thanks!

EDIT: When I tried to upgrade to the developer subscription ($19/month) I can add all the info but the button to confirm payment doesn't even work so I am not sure what to do. The site seems very glitchy overall.

**Comment by Anubhav1001** [comment]
we are also facing same problem .. is there solution available?

**Comment by botletics** [comment]
My only potential solution right now is to upgrade the subscription. You will probably notice that if the device isn't online, when you type the URL in the browser it will say "device not found" or something like that. However, right when the device connects the URL will spin forever. This indicates aREST is restricting the call, so I'm guessing I'm over the 1000 call limit.

**Comment by botletics** [comment]
Marcho Schwartz emailed me and said it was a database issue but it's working now (confirmed).
