### ISSUE TITLE
Can't get it to work with arduino-mqtt library

### ISSUE THREAD

**Issue by rlesac** [marcoschwartz/aREST#150]
I use the arduino-mqtt as it  supports SSL MQTT connections.
I can't get them to work together. 
My guess is that the loop handling is the problem.
MQTT client is only parsing data after there aREST receives data.

**Comment by marcoschwartz** [comment]
Definitely the problem is with the library as I didn't plan aREST to work with anything else than PubSubClient :) What is the link to the library you try to use so I can have a look?

**Comment by rlesac** [comment]
Hi, got it to work in the mean time.
It's on GiHub: [https://github.com/256dpi/arduino-mqtt](url)

I adjusted the loop a bit:
`void loop() {
  mclient.loop();
  delay(10); // <- fixes some issues with WiFi stability
   
  // Handle Local aREST calls
  WiFiClient clientLocal = server.available();
  if (!clientLocal) {
    return;
  }
  
  while(!clientLocal.available()){
    delay(1);
  }

  rest.handle(clientLocal);

  if (!mclient.connected()) {
    mconnect();
  }
}`

**Comment by marcoschwartz** [comment]
Awesome :)
