### ISSUE TITLE
help with aREST in App inventor for "Control ESP8266 anywhere" 

### ISSUE THREAD

**Issue by getoledo** [marcoschwartz/aREST#151]
Hello my friend.
First of all thank you for sharing your knowledge with everybody ! (and sorry my english i speak spanish) 
I use your example of "Control ESP8266 anywhere" into a ESP8266,I tried to control it using a web browser(cloud.arest.io/ ect)  of my computer,  and works fine.

But when I use a simple appinventor app to control using my android phone, it doesnt work.
When the screen1 intitialize I can see the "responsecontent" in label2,and also the inbuilt led of 8266 on, but when I use the buttons 1 2 or 3, I dont have "responsecontent in label2, and the inbuilt led doesnt change....( I am newby )

I wonder if you can help me , please.
Thank you in advance, my best regards.
Gerardo

![imagen](https://cloud.githubusercontent.com/assets/27635322/25072847/665cc198-22af-11e7-9500-8ca1d54ea576.png)

**Comment by getoledo** [comment]
Hello again !
I find it out just after write you. It was the "http" instead of "https"....
Sorry and thank you !

**Comment by marcoschwartz** [comment]
No worries :)
