### ISSUE TITLE
Eliminate or Debug Error 504 Gateway time-out

### ISSUE THREAD

**Issue by nandorrb** [marcoschwartz/aREST#155]
### Problem
I've got a recurring #152 problem with server. That error is in summary: ***after continuos use, device ID becomes unusable.***
My ID is [000000](https://cloud.arest.io/000000) . I can change device's ID, however problem will persist. 

### Warning
I think If someone creates a ***random ID's generator***, all ID's will break in no time.

### Possible Solutions
 1. I think it's necessary to add a way for debugging, maybe a message like:
```json
{"message":"ERROR_XXX: there are X devices using the same ID, please use another one."}
```
  of maybe:
```json
{"message":"ERROR_XXX: server error, please try again later."}
```
2. Add a ***SECRET KEY*** on device, and prevent other devices to use the same ID for X hours.

Thank you for your time.

**Comment by marcoschwartz** [comment]
Hi,

Indeed, this is a major issue that should be solved asap. I am currently on holidays, but will solve this as a priority once I come back. Actually aREST Pro already solves the issues with solution 2) as it uses an API key for your devices.

**Comment by nandorrb** [comment]
Very thank you @marcoschwartz  , I'll try aRest Pro also.
Please if you need any help, consider creating a repo of ***aRest Server***. I think a lot of people, including me, will love to help you to build this project and solve the bugs.

**Comment by marcoschwartz** [comment]
It is actually available here: https://github.com/marcoschwartz/meteor-aREST-mqtt, but unfortunately not up-to-date, I'll also focus on that when working on the issue

**Comment by nandorrb** [comment]
Thanks, I'll be keen on that repository.

**Comment by nandorrb** [comment]
Hi @marcoschwartz please don't forget about this issue, I really need to fix it

**Comment by marcoschwartz** [comment]
Hello,

I spent a lot of time to investigate the issue, I integrated a feature to automatically block new devices that would take the same ID, but my guess is that it was not the issue. Apparently when a device does not respond any more, the server just gets stuck in a loop waiting for an answer, which I think is what caused your issue. I'll now need to look into MQTT timeout settings to detect when to close a connection in case a device doesn't answer.

**Comment by gth311a** [comment]
I'm having the same (or similar) issue.  I assembled the [ESP8226 relay](https://openhomeautomation.net/control-relay-anywhere-esp8266) and use the code verbatim.  My relay is intended to be available "on-call" continuously for months at a time.  But I find that after a few days, it becomes unresponsive (and I start to get the 504 Gateway error).  I have had some success in the past by reuploading the Arduino code (changing only the device ID), deleting my dashboard, and creating a new one with the new device ID.  But even that was not fixing my problem today.  I have rebooted the ESP8266 many times and watched its status on the Arduino serial console, it seems to ALWAYS connect to wifi and log into the aREST server successfully, so I don't think that is the issue.  But it just seems like the device or dashboard inevitably "goes bad" after a few days.

**Comment by marcoschwartz** [comment]
Definitely seems like a server-side error indeed ... do you still have the issue since the last server update (3 days ago?)

**Comment by DarrylMG** [comment]
Hello:  I am sorta new with the cloud.arest.io and the Arduino esp8266. Over a year ago i had the relay_anywhere working just fine.  After a few days I put it aside due to other pressing things.  This week i fired up the sketch on my  ESP12E DEVKIT and it would not run??  Got a 504 timeout?  After much fooling around with getting latest aREST download and bunches of other fooling arounds it started working??? The only difference was the pins that control the leds on the board?? Anyway got it figured out and working just fine.  Guess what, no longer works, why? haven't a clue, but my problems sound very similar to a lot of complaints others have from what I read. I have tried changing all the changeable parameters , but that did not help at all.  Keep getting 504 timeouts now.
What am I doing wrong??
thank you

**Comment by DarrylMG** [comment]
Have been trying to get my ESP12E working with the simple relay anywhere sketch.  A few days ago it worked fine, then for no reason at all it no longer works.  After much fooling around i found that if my device_id is less than 11 characters it will eventually time out with no messages of any kind.  However if my device_id is 11 characters or more, I at least get a message back {"message":"Requested device not found"}  Why does that happen???  This has got to be something in the cloud.arest.io.
Thank you
any ideas anybody??????????
Darryl

**Comment by Froofus** [comment]
Hi Marco, I face the same problem as gth311a. I wish I could upgrade to a pro plan but i am out home for a while and won't be able to change my  esp8266 code any time soon ...
The thing is that i need to access my relay now... Is there any turn arround you can advice ? Should I send you my device ID so you can fix it ? 

Thx in advance

**Comment by marcoschwartz** [comment]
Hi everyone, there was indeed a lot of new users during the past days, which completely overloaded the free server. Now it's up again thanks to some improvements in the code - and of course I'll be monitoring it closely during the coming weeks. Sorry again about the issues!
