### ISSUE TITLE
errors with more than 5 functions

### ISSUE THREAD

**Issue by eadmaster** [marcoschwartz/aREST#156]
if i expose more than 5 functions i get garbage on the serial terminal and the whole sketch does not work as expected (functions get invoked randomly).

I am running [this sketch](http://eadmaster.altervista.org/pub/prj/electr/l9110_dcmotor_controller_arest.ino) on my CH340 Arduino Nano, compiled on Debian Jessie with the Arduino IDE v1.0.5 from the official repo.
I've also tried compiling with the latest IDE v1.8 and the results were the same.

**Comment by marcoschwartz** [comment]
Hello, by default aREST indeed limits the number of functions to 5 for memory reasons. If you need more functions you can use this at the start of the sketch:

#define NUMBER_FUNCTIONS 10

Let me know if that works :)

**Comment by eadmaster** [comment]
Allright, it is working fine now.
Can i increase the number up to 20 and are there any side-effect i should know?

**Comment by marcoschwartz** [comment]
Welcome :) Well you will quickly see compile errors if you reach the memory of your board, so I recommend just playing with the value :)
