### ISSUE TITLE
Arest.io webpage hangs

### ISSUE THREAD

**Issue by Mehatronicar** [marcoschwartz/aREST#169]
Webpage isnt responding at all, I tried on several devices and it is unresponsable but if I manualy type http://cloud.arest.io/xxxxx/digital/7/1 it works and it connects on RPI2 but webpage doesnt work. What is a problem?

**Comment by marcoschwartz** [comment]
Hello,

Sorry about the issue - it seems that the arest.io website and also the cloud server are up, what website do you have problem with exactly?

**Comment by marcoschwartz** [comment]
Hi - we are working on making it better, but please keep in mind that I am running it as a free service so our resources to run the server are limited and we are doing our best to keep up with the high number of new users lately (more than 6000 at the moment) :)

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer on this! We had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
