### ISSUE TITLE
Arduino Industrial 101

### ISSUE THREAD

**Issue by bbtimx** [marcoschwartz/aREST#172]
Hi

I would like to control my Arduino Industrial 101 with aREST.

Im using the BridgeServer.h and BridgeClient.h.

I extend the **aREST.h** with:

```
#elif defined(_BRIDGE_CLIENT_H_)
void handle(BridgeClient& client) {

  if (client.available()) {

    // Handle request
    handle_proto(client,false,0);

    // Answer
    sendBuffer(client,25,10);
    client.stop();

    // Reset variables for the next command
    reset_status();
  }
}

template <typename T>
void publish(BridgeClient& client, String eventName, T value) {

  // Publish request
  publish_proto(client, eventName, value);

}
```
Call in browser with `http://1.1.1.44/arduino/temperature` I get no response (HTTP ERROR 500).

It´s necessary to include the **/arduino/** path to redirect the call to the arduino.

I although try the **Yun.ino** example and get the result:
`Could not connect to YunServer 146 Connection refused`

**Comment by marcoschwartz** [comment]
Hello, interesting, I have to say that the Arduino Industrial 101 is not in the list of supported boards for aREST, so I never tried it on it. So I'll mark this as a feature request :)
