### ISSUE TITLE
Parameterless function

### ISSUE THREAD

**Issue by fynixtech** [marcoschwartz/aREST#18]
I am currently implementing some functions to turn on and off multiple devices. Since on and off only requires two states, I do not use the params part of the function. I simply check the last state of the pin and toggle as shown below

```
int switchCon(String c) {
  int state = !digitalRead(switch3);
  digitalWrite(switch3,state);
  return state;
}
```
Can you add the option for functions that do not need a parameter.

**Comment by potherca** [comment]
So... this can be closed, right?

**Comment by marcoschwartz** [comment]
Indeed, closing the issue.
