### ISSUE TITLE
Crashes with >5 custom functions

### ISSUE THREAD

**Issue by gsloan-qs** [marcoschwartz/aREST#181]
I'm running on an Uno R3.  Everything is working great, but I'm creating multiple different custom function calls and every time I register more than 5, the board resets when I make a REST call.

They are very simple functions (each one just blinks a digital output port). And I've thrown some memory checks in, there is consistatnly >400 bytes of SRAM free.  And it's not dependent on any specific function, I interchange which 5 are not commented out and it works fine. Add a 6th one, crash.

 Any idea why I'd be hitting this limit.

Incidentally, I could get around this if I could figure out how to pass more than 1 parameter into a function.

**Comment by marcoschwartz** [comment]
Hi, that's indeed a hard-coded limit for memory reasons :) You can change it by adding this line at the start of the sketch:

#define NUMBER_FUNCTIONS 10

**Comment by gsloan-qs** [comment]
Got it, makes sense. As it is, I figured out a way to do it all with a single function call anyway, so all good. But good to know.
