### ISSUE TITLE
comparing two C strings with ==

### ISSUE THREAD

**Issue by nathanejohnson** [marcoschwartz/aREST#20]
Starting on line 274:

        // Check for API key
        if(answer.startsWith("X-ApiKey")) {
          char * received_key;
          strcpy(received_key, answer.substring(10).c_str());

          if (received_key == api_key) {
          api_key_match = true;
            //Serial.println("API key match");
          }

Please excuse me if I'm missing something, I'm brand new to Arduino, but I see two things that at least appear to be problematic with the above code.  First, you call strcpy with the destination set as an uninitialized char pointer (received_key), and then you compare two char * strings with == instead of strcmp() or similar.  Am I missing something?  Or did you mean to use the String types there?  Or does the Arduino IDE automagically somehow convert char * to String ?

**Comment by marcoschwartz** [comment]
Added to my own to-do list, closing this for now.
