### ISSUE TITLE
Device API not working on free pro account

### ISSUE THREAD

**Issue by DraakAnubis** [marcoschwartz/aREST#216]
Ik have now 2 pro accounts and Both the accounts are not working ... i use the pro example code from Arduino aREST for the esp8266. IT gives me the text connected to aREST.io

Whats wrong ???

**Comment by marcoschwartz** [comment]
Hello, can you reach us at: contact@arest.io with your email? Then we'll check what is wrong in the account :)

**Comment by marcoschwartz** [comment]
Hi, we are investigating the issue at the moment - sorry about the issues!

**Comment by marcoschwartz** [comment]
Closing this as we moved free/pro accounts to pricing plans.
