### ISSUE TITLE
API key not securing device

### ISSUE THREAD

**Issue by akshay-rsm** [marcoschwartz/aREST#224]
The API key provided with a Starter account does work when commands are sent to my device in the following format: 
"pro.arest.io/device_id/mode/5/o?**key=your_key**"
But it also works when sent in the following format, without the API key:
"cloud.arest.io/device_id/mode/5/o"
Isn't it supposed to be secured through the API key? Or is that a feature provided for Pro accounts only?

**Comment by marcoschwartz** [comment]
Hi,

It would only work if you are using the API key in your sketch - is that the case? If not, indeed it will connect to aREST unprotected. We'll add a way to use an API key + 'forcing' a device ID into the sketches.

**Comment by Akshay-Rs** [comment]
I am using the API key in my sketch, as shown in the ESP8266_cloud_pro example. I controlled the device without the key initially. I flashed the sketch with the key after registering the device with arest.io. Do you think this might be the issue?

**Comment by marcoschwartz** [comment]
Hum, we'll need to dive into that - can you send me a message at contact@arest.io with your key so we can have a look?
