### ISSUE TITLE
aREST not working once again

### ISSUE THREAD

**Issue by DarrylMG** [marcoschwartz/aREST#225]
Marco:  The Relay Anywhere  seems to have reverted back to an earlier issue.  Seems now it only works if i change the ID.  This was an earlier Issue, would stop working until I changed the ID. Well its back to doing that once again.  Using 2.6.0 arest
Thank you
Darryl...

**Comment by marcoschwartz** [comment]
Hi Darryl, just answering there as I saw your other ticket. I'll check that on my end, however it seems work fine with our test boards.

However note that with unprotected IDs can be taken by someone else and should only be used for testing purposes. If you need to use your project on the long run, I'd suggest using an API key by going to  https://dashboard.arest.io/ and signing up for an account there.

Closing this for one - if you need additional help please email contact@arest.io :)
