### ISSUE TITLE
Need to call every URL twice

### ISSUE THREAD

**Issue by TD092854** [marcoschwartz/aREST#226]
Hi,

I'm having a problem where I have to call every aREST URL twice before it will respond with the correct answer. When it doesn't respond correctly it returns the default status message.

I've added my sketch, can you see what's wrong?

Thanks!
[aREST sketch.txt](https://github.com/marcoschwartz/aREST/files/1900532/aREST.sketch.txt)

**Comment by TD092854** [comment]
Some more information, it happens when I use analog input 4 as a digital input

**Comment by marcoschwartz** [comment]
Hey! Can you let me know which board you are using, as well as the version of aREST? Thx!

**Comment by TD092854** [comment]
I'm using an Arduino Uno with aREST version 2.7.1

**Comment by marcoschwartz** [comment]
Are you using it via Serial commands?
