### ISSUE TITLE
Missing {

### ISSUE THREAD

**Issue by eagler69** [marcoschwartz/aREST#24]
Hello,
Before anything else, thank you for sharing this amazing project! :)

I think I found a missing "{" at the aREST library.

When I use the default url, I mean, without parameters, the JSON answer is missing the first "{".
I think the problem is at line 632, where is the code: addToBuffer(F("\"id\": \"")); 
I think it should be: addToBuffer(F("{\"id\": \""));

Please forgive me if I'm wrong.

Best regards,
Eagler

**Comment by marcoschwartz** [comment]
This is now working, closing the issue :)
