### ISSUE TITLE
no matching function for call to 'aREST::handle(EthernetClient&)'

### ISSUE THREAD

**Issue by alvaroledesma** [marcoschwartz/aREST#248]
Arduino Keeps throwing this error whenever I try to compile the native Ethernet.ino file. Any ideas? 

`/Users/alvaroledesma/Documents/Arduino/libraries/aREST/examples/Ethernet/Ethernet.ino: In function 'void loop()':
Ethernet:71:21: error: no matching function for call to 'aREST::handle(EthernetClient&)'
   rest.handle(client);
                     ^
In file included from /Users/alvaroledesma/Documents/Arduino/libraries/aREST/examples/Ethernet/Ethernet.ino:12:0:
/Users/alvaroledesma/Documents/Arduino/libraries/aREST/aREST.h:734:6: note: candidate: void aREST::handle(HardwareSerial&)
 void handle(HardwareSerial& serial){
      ^
/Users/alvaroledesma/Documents/Arduino/libraries/aREST/aREST.h:734:6: note:   no known conversion for argument 1 from 'EthernetClient' to 'HardwareSerial&'
/Users/alvaroledesma/Documents/Arduino/libraries/aREST/aREST.h:758:6: note: candidate: void aREST::handle(char*)
 void handle(char * string) {
      ^
/Users/alvaroledesma/Documents/Arduino/libraries/aREST/aREST.h:758:6: note:   no known conversion for argument 1 from 'EthernetClient' to 'char*'
Using library SPI at version 1.0 in folder: /Users/alvaroledesma/Library/Arduino15/packages/arduino/hardware/avr/1.6.21/libraries/SPI 
Using library Ethernet at version 2.0.0 in folder: /Applications/Arduino.app/Contents/Java/libraries/Ethernet 
Using library aREST at version 2.7.3 in folder: /Users/alvaroledesma/Documents/Arduino/libraries/aREST 
exit status 1
no matching function for call to 'aREST::handle(EthernetClient&)'
`

@marcoschwartz

**Comment by alvaroledesma** [comment]
>I am also having this issue with an R3 and an Ethernet shield.  ...

@WDC I’m away from a computer right now but try this fix. 

Above the 

`aREST.h` header add this line of code. 
`#define ethernet_h`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcoschwartz** [comment]
I tool time to look into the issue, at the end it seems like there was a conflict with the Ethernet library from the Arduino Library Manager. With the Arduino standard Ethernet library I then had no compile errors. When using the other library and adapting aREST to use ethernet_h_, I had a ton of errors. So I'd suggest anyone using aREST & the Ethernet shield to stick with the official Ethernet library. Hope that helps!

**Comment by apetitjean** [comment]
Thanks Marco for the feedback.
Maybe you could do a blog post on this topic since I think a lot of people
(including me) are facing this issue (or will).


Le jeu. 13 sept. 2018 à 15:52, marcoschwartz <notifications@github.com> a
écrit :

**Comment by marcoschwartz** [comment]
Hi, just released a fix for that issue - I had some problems myself with my Arduino mixing up different Ethernet library installed on my computer :) Closing this for now, let me know if anyone still have some issues.

**Comment by henricazottes** [comment]
Hi, still have the issue :(
I have my ethernet shield on top of my arduino R3, using the Ethernet example from the library freshly downloaded with Platformio and I have the same error.

**Comment by davidusb-geek** [comment]
I had exactly the same problem here and upgrading to the latest version of the official Ethernet library solved this issue for me. Hope this helps someone out there.

**Comment by Bergerie** [comment]
Though the change log in Version 2.8.0 suggest that the issue was solved in version 2.7.4, I’m still getting the “no matching function for call to 'aREST::handle(EthernetClient&)'“ error. The Ethernet2 library is essential for me since the latest ethernet lib eats up too much memory such that the program can’t fit onto an UNO anymore. Any guidance to resolve this issue available?
