### ISSUE TITLE
helpanoob

### ISSUE THREAD

**Issue by 36abba** [marcoschwartz/aREST#256]
Arduino: 1.8.6 (Mac OS X), Board: "Arduino Uno WiFi Rev2, ATMEGA328"

esprfidtool:31:25: error: ESP8266WiFi.h: No such file or directory
compilation terminated.
exit status 1
ESP8266WiFi.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by K1ngjulien** [comment]
`ESP8266WiFi.h `doesn't exist, there's only `WiFi.h`, which is mapped to that library
