### ISSUE TITLE
compilie error by making a WiFi Weather Station With Arduino and the CC3000 chip

### ISSUE THREAD

**Issue by Getiteasygithub** [marcoschwartz/aREST#26]
I use the example from your website.

on 
 // Handle REST calls
  Adafruit_CC3000_ClientRef client = restServer.available();
  rest.handle(client);

i got an error : no matching function for call to 'aRest::handle(Adafruit_CC3000_ClientRef&)'
It looks like : it do not compile at a start at 
// Start server
  restServer.begin();
  displayConnectionDetails(); 
because i also have an error with that displayConnectionDetails();
the error say, he don´t found it in dht22???  

/Users/matthias/Documents/Arduino/libraries/aREST-master/aREST.h:79: error: redefinition of 'class aREST'
/Users/matthias/Documents/Arduino/libraries/aREST-master/aREST.h:79: error: previous definition of 'class aREST'
dht22.ino: In function 'void loop()':
dht22:116: error: no matching function for call to 'aREST::handle(Adafruit_CC3000_ClientRef&)'
/Users/matthias/Documents/Arduino/libraries/aREST-master/aREST.h:242: note: candidates are: void aREST::handle(HardwareSerial&)
/Users/matthias/Documents/Arduino/libraries/aREST-master/aREST.h:258: note:                 void aREST::handle(char*)

**Comment by lonneg** [comment]
What is required to install the module arest with npm? I can install express and jade with the command npm install. I am using windows 7. The error message seems to imply I need visual studio.

**Comment by marcoschwartz** [comment]
It should simply be:

npm install arest

But apparently there are issues with Windows, I am investigating that at the moment.

**Comment by lonneg** [comment]
I finally found the solution to installing arest on a windows 7 computer. You have to install Visual studio express 2010 and SDK. The 2010 express is the free version but is 32 bit, NOT 64. You then have to download the 32 bit version of Node.js

**Comment by marcoschwartz** [comment]
Interesting. Do you know why you need to install Visual studio specifically? For sure I'll add this into the documentation.

**Comment by lonneg** [comment]
It requires Visual C++ and the software development kit (SDK). I was able to find this out by many Google searches of the error codes generated after npm install of arest. I am having another problem when i run node app.js. I have updated the ip address in app.js to match the ip address generated when I run the weather station code in my arduino cc3000 combination. It says "error adding the device". I would appreciate any suggestions. I am almost finished on this project.

**Comment by equihuam** [comment]
I am having the same issue pointed out by @lonneg:  "error adding the device".  I am using node.js and following the same example mentioned by @Getiteasygithub about your article on *Open Home Automation*. I get this output about this when running `node app.js`:
>Sending request to address: 192.168.1.68 for variable id
>Error adding the device

I also notice that the output directly from the **arduino uno** is something like this (I edited a little bit the code to shorten names):
>{"temp": 20, "id": "1", "name": "WS

Which looks incomplete and I don´t know why.  I did eliminate most of the output to the serial port, because I had a problem of **memory** with global variables using 74% of the space!!!!! Was the only significant change to the code that I did. Eliminating those lines let the **arduino uno** upload like this:

>Sketch uses 29,320 bytes (90%) of program storage space. Maximum is 32,256 bytes.
Global variables use 1,530 bytes (74%) of dynamic memory, leaving 518 bytes for local variables. Maximum is 2,048 bytes.

**Comment by marcoschwartz** [comment]
This looks like an issue due to the latest versions of the Arduino IDE. Make sure to have the latest versions of all libraries (aREST, CC3000) and also use Arduino IDE 1.5.7. It is annoying & I hope Arduino will come up with a more stable version soon.

**Comment by lonneg** [comment]
The new libraries aREST and CC3000 fixed up the problem with adding the device. The only problem I have now is I can't get the temperature or humidity data from the arduino. The browser shows the Temperature and Humidity text but no data. The device reports "Online". I am using Arduino IDE 1.5.8

I really appreciate your help.

**Comment by marcoschwartz** [comment]
One thing to do now would be to see if there are any Javascript errors. Open the console in your browser and let me know if you see any bad stuff in there :)

**Comment by lonneg** [comment]
No, there are no javascript errors in the browser console. I am using Chrome for a browser.

**Comment by lonneg** [comment]
Upon further checking under the network tab, the status is reporting http://1.1.304 "not modified". This occurs every time a 'Get http;//local host:3000/weather_station/humidity or temperature' is sent.
Hope this helps.

**Comment by lonneg** [comment]
I am still struggling with this application. Could you tell me which javaScript file or program is writing the temperature and humidity data to my web server. I can see that data is being passed from the arduino by seeing it in the javaScript console. I should also point out that the units of measure are not getting to my web page (% or C). I would really appreciate any help you could give me as I feel very close to completing this project.

**Comment by marcoschwartz** [comment]
There is basically only one JavaScript file that queries the board for data, which should be located in the public/js folder of the app.

**Comment by lonneg** [comment]
Thanks for your help. I just installed the DHT11 sensor today and the data and engineering units began working on my web browser.I didn't have this sensor at the time and didn't think it would affect the engineering units, and mavbe the data would show up as some negative value.Anyway it works great.

**Comment by marcoschwartz** [comment]
Excellent! Closing the issue :)
