### ISSUE TITLE
Server problems

### ISSUE THREAD

**Issue by dukestrauss** [marcoschwartz/aREST#266]
Is the aRest platform being supported anymore?

**Comment by iolarha** [comment]
I'm wondering the same thing

**Comment by mamvcivm** [comment]
I tried a Random Nerd Tutorial using Arest about 6 weeks ago and it was working perfectly. I now find I cannot log into the dashboard website, nor reset my password, nor create a new account - the contact address is https://arest.io/contact@arest.io which simply presents a blank webpage. I did wonder whether I had accidentally signed up to a cloned website...

**Comment by ankittaneja** [comment]
Same here! I was going to use it for a demo for 25 people. I guess would I need to write an own MQTT Broker.

**Comment by mamvcivm** [comment]
Perhaps this is the nature of the beast - there are so many IoT sites out there that none will have dependable longevity...

**Comment by ankittaneja** [comment]
@mamvcivm : Can you please provide link to a similar library? I am in dire need of this and would avoid writing something on my own.

**Comment by mamvcivm** [comment]
@ankittaneja hi Ankit. Sorry, I don't have the ability to do that  :-(

**Comment by marcoschwartz** [comment]
Hi, I want to assure everyone that the project is far from dead - we are working on deploying a new version that will be able to handle the current load of users. Note that aREST is a free project, therefore we can't just pay more to have bigger servers, we need to find other solutions which means in the present case rewriting some of the code :) We'll make an announcement once the new application is online.

**Comment by ankittaneja** [comment]
Hi @marcoschwartz ,

First of all thanks for this amazing project! Secondly, can you give us any timeline when it will be online again? And last, is there a way I can contribute. I used C++ last in 2011, but can help with javascript if you are using that now! Or preparing video / writing blog articles, I remember you sent an email few months back regarding the same.

**Comment by marcoschwartz** [comment]
Thanks! I think the core cloud functions will be back up quite quickly, as it's really just transposing code from Meteor to Node.js, with some modifications of course. So I expect this to be up at the beginning of next week. For the dashboard, it might be a little longer as I want to convert it to VueJS for a much easier maintenance in the future. For sure when it's all back up I'd be happy to use your help to prepare videos & blog articles, it's much appreciated :)

**Comment by marcoschwartz** [comment]
I am happy to announce that the new cloud server is already live! Of course, you will need to update your libraries to the next version for your devices to work with the new server. I'll now work on the graphical interface part, hope to have it available by next week :)

**Comment by ankittaneja** [comment]
Hi @marcoschwartz ,

1. I am getting "Cannot Get /" when trying to visit cloud.arest.io
2. Since I am doing a workshop, I created a web app so everyone can have there own server. Have a look when you have time: https://github.com/ankittaneja/yd19-webapp 
(Still need to give it finishingl touches)

Co-incidentally, I am also using VueJS for a new project.(Although, my colleague also showed lit-element, have a look).

Vielen Dank und Grüß aus Berlin :)

**Comment by yvesd3** [comment]
I am getting Error 404 gateway time-out error from cloud.arest.io 's side. Is this happening with anyone else?

**Comment by zach27** [comment]
I'm encountering a different but possibly related problem. I'm unable to create an account on arest.io. Clicking the buttons on the UI does nothing. (I'm seeing the same behavior in multiple web browsers.) Anyone else seeing the same?

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer on this! We had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
