### ISSUE TITLE
aRest.h compilation error

### ISSUE THREAD

**Issue by ai04yc01** [marcoschwartz/aREST#268]
This library is great. But when I tried to compile it with Firebase client (#include "FirebaseESP8266.h"), a bunch of errors occurred.

In file included from C:\Users\User\Documents\Arduino\arduino-wifi-firebase-lightstrip\arduino-wifi-firebase-lightstrip.ino:38:0:

C:\Users\User\Documents\Arduino\libraries\aREST/aREST.h: In member function 'void aREST::send_http_headers()':

C:\Users\User\Documents\Arduino\libraries\aREST/aREST.h:453:190: error: no matching function for call to 'aREST::addToBufferF(const char [158])'.....

As FirebaseESP8266.h must be followed by ESP8266WiFi.h, moving the position of aREST.h anywhere before, in-between and after the 2 libraries will yield mixed error messages.

Any insights on how to fix?

**Comment by gcuendet** [comment]
I got the same issue on my Arduino UNO Wifi REV2 and found a related discussion [here](https://forum.arduino.cc/index.php?topic=674653.0) pointing to [another discussion](https://forum.arduino.cc/index.php?topic=653817.0) linking to a ["bug" in ArduinoCore-megaavr](https://github.com/arduino/ArduinoCore-megaavr/issues/62).

Apparently just defining `__FlashStringHelper` solves the problem:
```
#define __FlashStringHelper char
```

I added that just before including `aRest.h`, not sure if that's the best way, but it works.
