### ISSUE TITLE
Can't make function : https://cloud.arest.io/e49n2di/digital/5/1

### ISSUE THREAD

**Issue by Henitz** [marcoschwartz/aREST#269]
The command apear on the browser, but the relay doesn't work, a use before with another program.
I didn't made mistakes with the cables

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer to this issue! We make a lot of changes to the API & to the dashboard since then, please follow our official quick start guide to solve your issue: https://arest.io/quick-start
