### ISSUE TITLE
Can not see device in dashboard

### ISSUE THREAD

**Issue by Jepeto4** [marcoschwartz/aREST#271]
Hello Marco,

I sent you a few emails directly but did not get any response so far. I have been using your solution in the past without any problem but since you have changed server and dashboard recently (back in May I reckon), I am unable to see new devices in the dashboard.
I have of course used the latest version of aRest and I can successfully check the device in connected and responding via cloud.arest.io link. The issue is I don't have a clue on how getting it in the dashboard. Can you help?

**Comment by marcoschwartz** [comment]
Hi, sorry you didn't get an answer from our support - I'll check to see what happened there. Are you using your API key in the sketch? It is now necessary so the dashboard can now it is your device. Let me know if you need further help :)

**Comment by Jepeto4** [comment]
Thanks for the answer Marco,

I have tried also using the API key and in that case, the device is enumarated and shown connected but I can not get control of it.
I have actually sent you a few emails directly (under another address jp@nextitude.com <mailto:jp@nextitude.com>) explaining the problem in details.

What is frustrating is i have been using your solution before without any problem. It is just now i am returning to it after the changes you made that I am in trouble.

Regards,

Le 20 nov. 2019 à 18:45, marcoschwartz <notifications@github.com> a écrit :

Hi, sorry you didn't get an answer from our support - I'll check to see what happened there. Are you using your API key in the sketch? It is now necessary so the dashboard can now it is your device. Let me know if you need further help :)

**Comment by Jepeto4** [comment]
Hello Marco,

Do you understand why the drive is enumerating once just after it has been connected and then it is no longer seen alive and no functions can be set/displayed (tried the standard sketch with API key)?
Looking at the Arduino monitor screen I can't see no further status than connected to aRest just after the launch.

Regards,

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer to this issue! We make a lot of changes to the API & to the dashboard since then, please follow our official quick start guide to solve your issue: https://arest.io/quick-start
