### ISSUE TITLE
sending more than one parameter for function

### ISSUE THREAD

**Issue by OmiD-K** [marcoschwartz/aREST#273]
Hi
I want to send more than one parameter for my functions.
Is it possible?

**Comment by marcoschwartz** [comment]
Hello, indeed this is possible by using commas:

?params=foo,bar

**Comment by ONLYstcm** [comment]
When I pass a function with more than one argument in _rest.function_, I get the following error message: invalid conversion from _int (*)(String, String)' to 'int (*)(String)' [-fpermissive]_, so do we specify a function with more than one argument?
