### ISSUE TITLE
HTTPS instead of HTTP? (Question)

### ISSUE THREAD

**Issue by ONLYstcm** [marcoschwartz/aREST#276]
Just a quick question, I see aREST is over HTTP. Doesn't that mean information can be sniffed over a wireless network, if so would it be possible to implement a HTTPS server as opposed to HTTP.

**Comment by marcoschwartz** [comment]
Hello, all the aREST cloud requests are using HTTPS, and also the aREST devices communicate via a secure MQTT connection to the server :)

Of course locally it uses HTTP, we'll see if we can run an HTTPS server on some boards in the future.
