### ISSUE TITLE
arest dashboard do not show ID Device

### ISSUE THREAD

**Issue by xe2ad** [marcoschwartz/aREST#282]
I´m trying to set up the dashboard to just turn on & off a led, as a first test. I followed the sketch from "Internet of Things with Arduino Cookbook" and also from other sites and all of them configure the dashboard and write the id device while in the last  arest dashboard it has a menu that I can´t display, neither write my id device code.

Seems that there was an arest dashboard update or the way it has to be set up has changed. 

Hope I can get some help to just turn on & off a simple led using an arduino mkr1000 board.

Best regards,

David.

**Comment by marcoschwartz** [comment]
Hello, we had some issues with the aREST dashboard in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
