### ISSUE TITLE
ESP32 Disconnecting

### ISSUE THREAD

**Issue by sabemm** [marcoschwartz/aREST#287]
Hello! I really love your Job! I actually created an iPhone app just for your library. I noticed about a 5 months ago I cant get the ESP32 or ESP8266 connected for more than a day. Everytime disconnects and can't access anymore but when I ping the device it is connected. Any Ideas why this could be happening? The only thing I added to the code is DHT library and I have a soil sensor  nothing else, even I have left just the default code and just cant get it to connect after a day until I manually reset it. Please help! 

The reason I suspect is the aRest library is because Im running a normal web server on ESP32 and 8266 and I haven't had any issues for 30 days now.

**Comment by martinius96** [comment]
Maybe Root CA and fingerprint has changed. If you are using MQTT over SSL. That can be common issue.

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer on this! And congrats for creating an app for aREST, do you mind sharing it here? Or is it for private use?

About your problem, we had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
