### ISSUE TITLE
arest.io problem

### ISSUE THREAD

**Issue by LightSN** [marcoschwartz/aREST#288]
Hi, 
I got problem with cloud.arest.io (502 bad gateway) and with dashboard.arest.io not loading

**Comment by marcoschwartz** [comment]
Hi, sorry about that - we have an issue with the host of our database (DigitalOcean), we are actively working on it and hope to have it fixed by tomorrow

**Comment by TiiFuchs** [comment]
Any news? It appears to be still a problem...?

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer on this! We had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
