### ISSUE TITLE
Python calls to Library

### ISSUE THREAD

**Issue by fischerjade** [marcoschwartz/aREST#29]
First of all thank you for the libraries and the documentation, they have been very helpful.  I have an issue though.  I am trying to make rest calls to the CC3000 and it doesn't seem to work even though I can ping it.  I have also created my own variables and were able to retrieve them through the URL.  EX. http://192.168.0.100/temperature.  I want to access it through Python so I tried:

import urllib2
response = urllib2.urlopen('http://python.org/')
html = response.read()
print html

We even tried to output this to a file and retrieve it with a browser and we can't retrieve anything from the CC3000 it just hangs.  This python code will work though.  We were able to get html pages from the Raspberry Pi web server in this manner.  

I know java script might work but I really want to use Kivy with python and retrieve my variables from the CC3000 so I can display them with python.  Any help would be appreciated.

**Comment by marcoschwartz** [comment]
Closing this now :)
