### ISSUE TITLE
Unable to create a new account

### ISSUE THREAD

**Issue by zach27** [marcoschwartz/aREST#291]
I'm unable to create a new account from the page `arest.io/pricing`. Clicking the "Create an Account" buttons does nothing, and I've tried in multiple browsers and have gotten the same behavior.

There's an error in the console that could be related:
![image](https://user-images.githubusercontent.com/6356025/100492524-f8db2200-30fa-11eb-8fe6-43cea2142d1b.png)

I've also tried directly submitting the form at `arest.io/signup`, but this does nothing as well.

**Do we have an ETA when this will be fixed?** I'd like to use this framework to build a REST API, but it's looking like I'll have to go with an alternative, considering other people are having basic reliability problems with the site. Thanks for your consideration.

**Comment by Stewrat007** [comment]
I'm having similar problems to this. I have tried to setup an account from the Pricing page 'Create an Account', which seems to go OK but I do not receive an email and I cannot open my account - in fact I don't appear to have one.

This is very disappointing as this system shows great promise but fails even before I get in.

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer on this! We had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!
