### ISSUE TITLE
'class aREST' has no member named 'get_topic'

### ISSUE THREAD

**Issue by JRameshJayaram** [marcoschwartz/aREST#294]
Dear Marco,

aRest is simply awesome. I really love your work. Thank you so much for everything that you have done so far.
Well, while compiling one of your codes, I'd encountered a problem. 

Error:

Arduino: 1.8.13 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\My Home Automation\Control_Relay_from_Anywhere.ino: In function 'void setup()':

Control_Relay_from_Anywhere:47:26: error: 'class aREST' has no member named 'get_topic'

   char* out_topic = rest.get_topic();

                          ^

exit status 1

'class aREST' has no member named 'get_topic'

I hope you could shed some lights on this. Thank you in advance mate.

Best wishes,
J.Ramesh

**Comment by marcoschwartz** [comment]
Thanks for reporting this bug, we'll work on it!

**Comment by marcoschwartz** [comment]
This is now fixed in the latest release, make sure to use the official examples sketches that we have updated :)

**Comment by hoh1114** [comment]
Hi Marco,

I just start to learn how to use aREST but I encounter the same problem after  I delete the previous libraries and download back 

error : 

exit status 1

'class aREST' has no member named 'get_topic'

I hope you can provide some guidance thank you very much 

Best Regard
hoh
![error](https://user-images.githubusercontent.com/85052827/120095855-d504a180-c15a-11eb-8c66-630a663a3b46.png)
