### ISSUE TITLE
ethernet_cloud sketch don't run

### ISSUE THREAD

**Issue by flaviopalermoiot** [marcoschwartz/aREST#296]
Hello, I'm a new user, I installed his library today.
I did some tests with the ethernet_cloud sketch, I also had to install the PubSubClient-2.8.0 library, because the sketch gave me an error at line 13 #include <PubSubClient.h>. Now it gives me an error on line 57 which I don't understand. I attach error message. Thank you in advance . Kind regards Flavio Palermo

Arduino:1.8.13 (Windows 10), Scheda:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Z:\Arduino prg\Ethernet_cloud_arest\Ethernet_cloud_arest.ino: In function 'void setup()':

Ethernet_cloud_arest:57:26: error: 'class aREST' has no member named 'get_topic'; did you mean 'out_topic'?

   char* out_topic = rest.get_topic();

                          ^~~~~~~~~

                          out_topic

exit status 1

'class aREST' has no member named 'get_topic'; did you mean 'out_topic'?

**Comment by marcoschwartz** [comment]
Hi, thanks for reporting this one - will test it on my own Ethernet board and update this!

**Comment by marcoschwartz** [comment]
This is now fixed in the latest release!
