### ISSUE TITLE
https://dashboard.arest.io/devices is not providing any way to add devices

### ISSUE THREAD

**Issue by david-w-t** [marcoschwartz/aREST#297]
I do not see any way to add a device, which is preventing me to add anything to a dashboard.  So, its impossible to do anything on arest.io.

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer to this issue! We make a lot of changes to the API & to the dashboard since then, please follow our official quick start guide to solve your issue: https://arest.io/quick-start
