### ISSUE TITLE
Add support for UIPEthernet

### ISSUE THREAD

**Issue by tlindener** [marcoschwartz/aREST#30]
Hi,

would you be willing to add support for the UIPEthernet library? It is basically a dropin replacement for the standard Ethernet library. But unfortunately you check for usage of ethernet_h which creates compiler errors at the moment. 

You just have to add this peace of code 
"/ Handle request for UIPEthernet lib
#elif defined(UIPETHERNET_H)
void handle(UIPClient& client){

  if (client.available()) {

    // Handle request
    handle_proto(client,true,0);

    // Answer
    sendBuffer(client,50,5);
    client.stop();  
   
    // Reset variables for the next command
    reset_status();   
  }
}

I can also create a pull request if you prefer this...

**Comment by marcoschwartz** [comment]
Hi, sure, that's a great idea! I will include that in the next revision of the aREST library, no need for a pull request. Thanks!
