### ISSUE TITLE
Does aREST support the Arduino Uno WiFi r2 Board ?

### ISSUE THREAD

**Issue by djipco** [marcoschwartz/aREST#303]
Does the aREST library support the Arduino Uno WiFi revision 2 Board ? This board, like the Arduino MKR WiFi 1010, Arduino MKR VIDOR 4000 and Nano 33 IoT, is using the [WiFININA library](https://www.arduino.cc/reference/en/libraries/wifinina/).

I believe the API is almost identical to the original Wifi library so it should be possible to add support for it without too much effort. Is that under consideration?

**Comment by marcoschwartz** [comment]
Hi! Never tried it with this board, but if it's close to the MKR board it should work. Do you have any error you could share when trying to compile the example MKR 1000 code with this board?

**Comment by djipco** [comment]
I just tried it with the [MKR1000.ino](https://github.com/marcoschwartz/aREST/blob/master/examples/MKR1000/MKR1000.ino) sketch and I do not get any compilation errors after changing `#include <WiFi101.h>` for `#include <WiFiNINA.h>`. In the serial monitor, it says the wifi is connected and the server is started. 

I am able to query a pin for status but I'm unable to turn on the onboard LED. I'm not sure if I'm the problem or if there is an issue with the compatibility.

**Comment by marcoschwartz** [comment]
Hi, that's good progress :) By onboard LED you mean some board integrated on your Arduino board? did you try with an external LED?

**Comment by djipco** [comment]
It's working! I guess I had not set the pin to be an output. This is using v2.9.6. In the end, all I had to do was swap `#include <WiFi101.h>` for `#include <WiFiNINA.h>`.
