### ISSUE TITLE
Read all digital, analog and variable values with one request

### ISSUE THREAD

**Issue by stephanmarks** [marcoschwartz/aREST#32]
Hi

I am currently using your library to communicate with openhab via REST
It would be nice if I can get all Data form an arduino ATMega328 with one Request. 
Example:
  http://[IP]/alldata
returns a complete JSON-String like this 
{"alldata":
	{"digital":
		[{"value":0}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":0}],
	"digital":
		[{"value":0}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":0}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":0}],
	"digital":
		[{"value":0}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":1}],
	"digital":
		[{"value":0}],
	"analog":
		[{"value":100}],
	"analog":
		[{"value":220}],
	"analog":
		[{"value":50}],
	"analog":
		[{"value":80}],
	"analog":
		[{"value":90}],
	"analog":
		[{"value":90}],
	"variable":
		[{"functionname": "temperature", "value":22},
		{"functionname": "humidity", "value":95},
		{"functionname": "NNN", "value":"Next"}]
	}
}

I would be verry happy if you will add this function

Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
Hey Stephan, interesting project you have there! Well for now what you want is possible in three requests:

/digital/a for all digital pins
/analog/a for all analog pins
/ (without anything else) for all variables that are then in an array called variables

Is that ok for you or you really need all in one request?

**Comment by stephanmarks** [comment]
Hey Marco, 

many thanks for your answer. Your suggestion is better as mine. In most cases I only need the digital states and i think it is more easier to loop over the array.

Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
Excellent! Closing the issue then. If you have some project to show in the future contact me directly if you want it to be featured on the aREST.io website!
