### ISSUE TITLE
redefinition / previous definition of 'class aREST' 

### ISSUE THREAD

**Issue by stephanmarks** [marcoschwartz/aREST#37]
Hello Marco,

I have some trouble using Eclipse as IDE with your usefull aRest-Lib. If I use the Arduino IDE 1.6.0 or 1.6.3 there is no Problem. I can compile and upload the Sketch with aREST.h and Ethernet.h.

Last month I decide to use Eclipse instead of the Arduino IDE. All went well and I use Libs like dht.h, mySensors.h, OneWire.h and so on. But if I use the aRest.h lib I get this error
..../Arduino/libraries/aREST-master/aREST.h:79: error: redefinition of 'class aREST'
..../Arduino/libraries/aREST-master/aREST.h:79: error: previous definition of 'class aREST'

I found the Issue 26 but I think that won't solve my case. I use the latest Build 20150401 for Linux 64 Bit from www.bayens.it/eclipse with the 1.6.0 Arduino. I tried its also with 1.6.3 und 1.5.8 but there are additional Problems but it solves not the main Problem.  

Have you any Idear or Hint

Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
Hello Stephan, thanks for using the library! Well I never used Eclipse before, but it seems that the naming is wrong for the folder of the library:

..../Arduino/libraries/aREST-master/aREST.h:79: error: redefinition of 'class aREST'

should be:

..../Arduino/libraries/aREST/aREST.h:79: error: redefinition of 'class aREST'

I would try that first and then try again.

**Comment by stephanmarks** [comment]
Hello Marc, thanks for your answer. I have changed the naming of the library. I also used your actual library. But the result is the same.

/home/stephan/Anwendungen/Arduino/arduino-1.6.0/libraries/aREST/aREST.h: At global scope:
/home/stephan/Anwendungen/Arduino/arduino-1.6.0/libraries/aREST/aREST.h:93:7: error: redefinition of 'class aREST'
 class aREST {
       ^
In file included from ../.ino.cpp:9:0:
/home/stephan/Anwendungen/Arduino/arduino-1.6.0/libraries/aREST/aREST.h:93:7: error: previous definition of 'class aREST'
 class aREST {
       ^

Have you some other ideas?

**Comment by stephanmarks** [comment]
Hello Marco, I have tried your ethernet-example with the same error.
Than I have tried the following. I add some Preprocessorstatements to prevent that your librarie will be included multiple. Now I can compile my Code und your exampel without Problems. It seems that the librarie is imported multiple. The Statements I have added are marked bold in the Codesnip above. Perhaps this may help you.

/* 
  aREST Library for Arduino
  See the README file for more details.
 
  Written in 2014 by Marco Schwartz under a GPL license. 

  Version 1.9.8
...
...
...
<B>#ifndef aRest_h
#define aRest_h</B>
  // Include Arduino header
  #include "Arduino.h"
  // Using ESP8266 ?
  #if defined(ESP8266)
  #include "stdlib_noniso.h"
  #endif
  ...
  ...
  ...
  // Functions array
  uint8_t functions_index;
  int (*functions[NUMBER_FUNCTIONS])(String);
  char * functions_names[NUMBER_FUNCTIONS];
};
<B>#endif</B>

**Comment by marcoschwartz** [comment]
Ok, I made the suggested modification. Let me know if that works!

**Comment by stephanmarks** [comment]
Hello Marco,

I have checked with Windows 32 Bit Eclipse and Linux 64 Bit Eclipse. Also I make a test with Linux 64 Bit Arduino IDE 1.6.0. All went good. But I am not sure if the position of the statement is the best.  Therefore I moved the statement just before the class definition and do the test above again.  This works also. Perhaps this will be a better solution but this is up to you.   
Example:

.....
<B>#ifndef aRest_h
#define aRest_h</B>

class aREST {

public:

**Comment by marcoschwartz** [comment]
Happy to know that it works now! I don't think the location of this statement is important at the moment, but if needed I'll move it in the future. Closing the issue now :)

**Comment by stephanmarks** [comment]
Hi Marco,
it seems as if you moved accidentally the #endif Preprocessorstatements form the end to the beginning. Therefore the Problem is back. 
Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
Hi Stephan,

That might have happened, I just made a fix, can you test it ?

**Comment by stephanmarks** [comment]
Hi Marco,
I made a quick check. Now it works as before. Thanks!
Best wishes
  Stephan
