### ISSUE TITLE
ESP8266 / aREST compile issue "'F' was not declared in this scope"

### ISSUE THREAD

**Issue by jasonslay** [marcoschwartz/aREST#38]
I am trying to compile the example using the ESP8266 Arduino IDE 1.6.1 and aREST installed as instructed. After selecting generic ESP8266 as the board, I verify and the compilation fails with the following error:

Arduino/libraries/aREST/aREST.h:898:38: error: 'F' was not declared in this scope
     Serial.print(F("Sending buffer: "));

Any ideas?

**Comment by marcoschwartz** [comment]
Thanks for letting me know! It seems that it depends on wether you are using the ESP8266 Arduino IDE from the release or build it from the source. 

I just published a fix, let me know if it works now.

**Comment by marcoschwartz** [comment]
I made more tests and for now the only way is indeed to build from the source. I added this as a comment in the README file.

**Comment by jasonslay** [comment]
Looks like that worked. Compiling without errors now. Thanks!

**Comment by marcoschwartz** [comment]
Great! Closing the issue.
