### ISSUE TITLE
WiFi CC3000 example sketch seems too large

### ISSUE THREAD

**Issue by aiueoH** [marcoschwartz/aREST#41]
Sketch uses 30,838 bytes (107%) of program storage space. Maximum is 28,672 bytes.

Does anyone has same problem ?

**Comment by marcoschwartz** [comment]
Hello, what board are you using? If it's a Leonardo unfortunately it doesn't have enough memory to contain aREST + the CC3000 library.

**Comment by aiueoH** [comment]
So sad, I use leonardo right :(

Actually my board is WiDo, it's composed of leonardo and CC3000. I'll try others solution, thanks for your reply and library :D

**Comment by marcoschwartz** [comment]
You're welcom!
