### ISSUE TITLE
ESP8266WiFi.h: No such file or directory

### ISSUE THREAD

**Issue by g1ra** [marcoschwartz/aREST#42]
```
$ git clone https://github.com/esp8266/Arduino.git
$ cd Arduino/build
$ ant dist
$ ...
$ cd arduino-1.6.1/libraries
$ git clone https://github.com/marcoschwartz/aREST
```
 I got this error : ESP8266.ino:9:25: fatal error: ESP8266WiFi.h: No such file or directory

**Comment by marcoschwartz** [comment]
Looks like you didn't select "Generic ESP8266 WiFi board" in the Arduino IDE. Can you check that?

**Comment by g1ra** [comment]
Yes. That was the problem. 

Meanwhile I cloned  https://github.com/ekstrand/ESP8266wifi into libraries. 
Do you use ekstrand's ESP8266?

Now should work (?) after I figure out how to connect the board. 
What is the recommended way to upload a sketch to ESP8266? May I use a FTDI serial to USB adapter? 
I have a ESP-07 module . 
This : 
![esp-07v2](https://cloud.githubusercontent.com/assets/1227764/7154160/4aa8c25a-e353-11e4-86a1-e8019cdf2f31.jpg)

**Comment by g1ra** [comment]
... I found this [Installing and Building an Arduino Sketch for the $5 ESP8266 microcontroller](http://makezine.com/2015/04/01/installing-building-arduino-sketch-5-microcontroller/ )

**Comment by efifi** [comment]
where do you find this file - ESP8266WiFi.h

you can see it in the IDE when selecting the correct board but i cannot find it in my windows file structure?

**Comment by marcoschwartz** [comment]
Well you don't need to locate it yourself - when you select the correct board in the IDE it gets available by default.

**Comment by lesjaw** [comment]
so basiically we cant use ESP8266WiFi.h if we choose arduino as board?

i really want to use that library, because my esp8266 attached to my arduino, i want to make a IR transmitter, which is connected to my Wifi network... since esp8266 self lack of real pwm pin

**Comment by marcoschwartz** [comment]
Yes indeed. Well from what I know the ESP8266 PWM works just fine, I used it just this morning :) From the official GitHub repository:

analogWrite(pin, value) enables software PWM on the given pin. PWM may be used on pins 0 to 15. Call analogWrite(pin, 0) to disable PWM on the pin. value may be in range from 0 to PWMRANGE, which is currently equal to 1023.

And of course it's supported by aREST :)

**Comment by marcoschwartz** [comment]
Closing this issue

**Comment by vijaykumarmishra** [comment]
ESP8266_SoftSer.h: No such file or directory(progamme to remote  control car)
 program i tried too much blynk libraries but no one work......
please help me .....
email me a solution at  rockingvijay996@gmail.com

**Comment by marcoschwartz** [comment]
Hello, are you sure it's a problem with aREST? aREST doesn't use ESP8266_SoftSer.h and also you are mentioning Blynk :)

**Comment by vijaykumarmishra** [comment]
I am taking program to control remote control car by blynk app but it not
work
Please suggest me what to do???

On Aug 22, 2016 10:02 PM, "marcoschwartz" <notifications@github.com> wrote:

Hello, are you sure it's a problem with aREST? aREST doesn't use
ESP8266_SoftSer.h and also you are mentioning Blynk :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/marcoschwartz/aREST/issues/42#issuecomment-241470636>,
or mute the thread

**Comment by marcoschwartz** [comment]
Sorry, this is only for aREST related issues. For Blynk you can go to their GitHub repository :)

**Comment by marcoschwartz** [comment]
Again, this is the aREST repository, which has nothing to do with Blynk. Please only post issues with aREST. Thank you.

**Comment by Netzsolutions** [comment]
Thanks for your pro-active responses. I was going through few forums and saw your ones. I was getting some error due to non availability of esp8266wifi.h; and I believe I got the issue. I believe I was not selecting the right board. I will try today. Thanks

**Comment by imvickykumar999** [comment]
> Well you don't need to locate it yourself - when you select the correct board in the IDE it gets available by default.

...how to select, and from where to select board ?
