### ISSUE TITLE
Error when using http://[IP-Adr]/digital/a

### ISSUE THREAD

**Issue by stephanmarks** [marcoschwartz/aREST#44]
If i use the statement http://[IP-Adr]/digital/a to get al digital Values I got a result like this
{"D0": 1, "D1": 1, "D2": 1, "D3": 1, "D4": 1, "D5": 1, "D6": 0, "D7": 1, "D8": 0, "D9": 1, "D10": 1, "D11": 1, "D12": oÿ@<86znnected": true€

I am using Arduino Nano ATMega328. 
After this request the Led L is flickering and I can not contact to Arduino via REST. Ping is working. 
Themes that there is a Memory problem.

**Comment by marcoschwartz** [comment]
Hello Stephan,

Can you tell me which hardware are you using to access the board? You mentioned pinging the board, are you using WiFi, Ethernet? Thanks

**Comment by stephanmarks** [comment]
Hello Marco,

I am using the Ethernet Chip W5100. I tried this statements several times and I have different results. Sometimes the arduino dies and sometimes I get only this strange result. The assumption with ping was wrong. I made an mistake and therefore it seems that the ping is working. 

Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
Strange indeed. I don't have a Nano at hand but I'll do some tests with an Uno + the Ethernet shield, I'll keep you posted.

**Comment by marcoschwartz** [comment]
Ok got it, it was an issue with the output buffer size. I just released a fix, let me know if that works!

**Comment by stephanmarks** [comment]
Hell Marco,
now the result is correct. Thanks for your work. 
Best wishes 
  Stephan

**Comment by marcoschwartz** [comment]
You're welcome!
