### ISSUE TITLE
Connection resets with mobile interfacing

### ISSUE THREAD

**Issue by worldofpayne** [marcoschwartz/aREST#45]
I am using an Arduino Mega with the CC3000 wi-fi board. I have a C# app that communicates with asynchronous get commands flawlessly but any command from the android app I am building or from the browser on the phone causes the connection to reset and have to go through setup again. I had the same problem with the PC app but that resolved when you updated the library recently. Any kind of fix or understanding as to what is going on and why the phone causes a different result would be appreciated. It seems that you offer great support to anyone with a problem and I thank you for that.

**Comment by marcoschwartz** [comment]
Hello,

Thanks for using my library! This can be due to many factors. For example if you send commands too quickly without properly reading the answer from the board it will crash for sure. Are you doing some kind of async calls that might be sent to the board in the same time?

**Comment by worldofpayne** [comment]
I noticed in your newer examples you removed the wdt library and the associated commands. After doing that the arduino no longer resets however in a way the same problem is there. I find I can spam commands as much as I want with the async commands from my pc but any command from mobile app it will execute the command and then there is 40 to 50 second delay until any more commands will be executed at all. Its hard to know how the phone app is handling answers though since I am using MIT's App inventor website and though I have it set to ignore returned results, again I can't know with that software. I don't know if any reason jumps to mind for this or if there is a way I'm not thinking of to keep it all on track.

**Comment by marcoschwartz** [comment]
Interesting. I don't know much about Android app development (but that's something I want to explore in the future!) but I imagine that the more "basic" the request to the board is, the better for the board and aREST. So I don't know what the MIT inventor app is using, but a simple cURL call should be enough.

**Comment by worldofpayne** [comment]
Is there any way to disregard any potentially complex way the get command is implemented from the app inventor on the arduino side and just execute the function and keep things moving as normal afterwards since I can't control how the website does things? Like I said it runs the function immediately, the delay/stall occurs afterwards so it seems like it could be avoided with everything working fine
