### ISSUE TITLE
Web Based aRest doesn`t function after update

### ISSUE THREAD

**Issue by orion9009** [marcoschwartz/aREST#46]
Hi... I`m using aREST for my Arduino Home Automation project.  I have problem with the aREST... previously before i updated the aREST my was project functioning well.  But after i updated the library, all my rest function does not respond properly (LED control function and custom functions).  After that, i revert back the library to the previous one then it`s working again.

For now, I revert back to aREST library from v 1.9.8 to v1.9.7 to stable operation.

FYI, I`m using Web based to control my Arduino.. I`m using the CuRL function.

**Comment by stephanmarks** [comment]
Please take a look at your command. The return value has changed. Now you got params=1 instead of 1. You must extract the 1 from the commandstring.

**Comment by marcoschwartz** [comment]
Hi, actually this was a bug that was introduced when fixing another bug. When you send the command:

function?params=1,2

You should really get 1,2 in the sketch. I just released a fix, let me know if it works better now.

**Comment by orion9009** [comment]
The fix works... now the functions return the expected value as I set in the code.  Thank you very much for the support.
