### ISSUE TITLE
The library doesn´t respond to the id or name

### ISSUE THREAD

**Issue by cfblanc** [marcoschwartz/aREST#49]
Hi!
I'm using the library with 2 Arduinos, each of them connected with an XBee, and I'm accesing the IO, variables and functions from another XBee connected directly to the PC. The problem is when I set the Destination Address of the XBee xonnected to the PC as Broadcast, both of the boards will answer in the same way, no matter if I use the name or ID defined in th REST library.
For example, if I put "serial1/digital/8/1" is the same as "serial2/digital/8/1" and in both case, both boards (the one named "serial1" and the "serial2" will activate pin 8).
This is like this or it's an error?
Thanks and best regards!

**Comment by marcoschwartz** [comment]
Hi! Thanks for using my library.

Well it depends what you are using on your computer, but yes it is like this, by default the messages will be broadcasted to all XBee modules. Are you using the node-aREST module to communicate between your PC and your XBee modules? If yes let me know I will redirect you to a tutorial to do exactly what you want to achieve :)

**Comment by cfblanc** [comment]
Hi! I-m connecting the PC with many Arduino boards (each of them has an XBee). So as not to change the Destination Address every time I want to send a message I want to put the destination in the Rest message.
Was I clear enough?
Thanks again!

Date: Wed, 20 May 2015 00:41:57 -0700

**Comment by marcoschwartz** [comment]
Sure got it :) Basically you need the Node.js aREST app for that, you can't do it with Serial commands only. I don't have a tutorial for that (but this is a good motivation to do one :) ), but here is an extract from a project of my book (http://www.openhomeautomation.net/home-automation-arduino/) using this:

```js
// Modules
var express = require('express');
var app = express();

// Define port
var port = 3000;

// View engine
app.set('view engine', 'jade');

// Set public folder
app.use(express.static(__dirname + '/public'));

// Rest
var rest = require("arest")(app);
rest.addDevice('xbee','/dev/tty.usbserial-A702LF8B');

// Serve interface
app.get('/', function(req, res){
  var devices = rest.getDevices();
  res.render('interface', {devices: devices});
});

// Start server
app.listen(port);
console.log("Listening on port " + port);
```

You will see all your XBee devices appearing on the console, with their IDs that you defined in aREST. Then you can call them via the Node.js server, for example:

http://localhost:3000/1/id

Hope that's clear enough :)

**Comment by cfblanc** [comment]
Is the Node.js aREST app free? Where can I get it? This is a PC software? Because my idea is to replace the PC with another Arduino with a touch LCD.Thanks again!

Date: Wed, 20 May 2015 11:31:26 -0700

**Comment by marcoschwartz** [comment]
Of course it's free :) You can find more information at:

https://github.com/marcoschwartz/node-aREST

And a basic tutorial at:

http://arest.io/server-http/

As this is not an issue with the aREST library I'll close the issue, but we can continue to discuss here :)

**Comment by cfblanc** [comment]
Marco,
I read the tutorial you sent me, but I have a doubt: at this moment I'm using 2 Arduino Board with an XBee each of them, the problems I have are:
In the example you use one WiFi board and the other serial, and I've two serial, but only one in the PC (I've an XBee connected to the PC, and that would be the one in the app.js but I've 2 XBee on the other side), so I can't access to a particular board.In the  apps.js file I can't find where to change the WiFi IP and the Serial port. Nevertheless, I think this won't help me, because I'll still have the problem I told you before. 
Thanks again and best regards!


PS: I changed your library so as it does what I want, but I doubt if you haven't solved it yet.

Date: Thu, 21 May 2015 00:55:50 -0700

**Comment by marcoschwartz** [comment]
Well the tutorial I sent you the link to is the only one I have so far about the Node.js aREST app, but for sure it doesn't cover XBee. I will come up with an XBee tutorial in the future, but no ETA yet :)
