### ISSUE TITLE
aREST on the Arduino Ethernet shield is not working

### ISSUE THREAD

**Issue by hemantkamalakar** [marcoschwartz/aREST#50]
Hi,
I am using the aREST Arduino library It is working fine with Serial example.
I am testing the Ethernet shield example I am getting the IP address (server is at 192.168.1.33
) assigned to my Ethernet shield. But when I try to access the GPIO pins via browser it is not working.

http://192.168.1.33/mode/7/o
http://192.168.1.33/digital/7/1

Error in IE : This page can't be displayed
Error in Chrome : This webpage is not available
ERR_CONNECTION_TIMED_OUT
Am I missing something?
Really appreciate your help.
Regards,
Hemant

**Comment by marcoschwartz** [comment]
Hi Hemant,

Thanks for letting me know, I'll test that right away!

**Comment by marcoschwartz** [comment]
Hello,

I just tested it and it works fine :) Can you tell me:

- which hardware you are using exactly
- which version of Arduino you are using

Also make sure to update to the latest version of aREST. Thanks!

**Comment by hemantkamalakar** [comment]
Hello,
I am using Arduino Uno and Arduino Ethernet Shield. I am using Arduino IDE ver 1.6.3.
Also tested with latest aREST library It is not working. 
I am getting the IP address assigned in Serial monitor (server is at 192.168.1.33
) 
But when I try to access the GPIO pins via browser it is not working.

**Comment by marcoschwartz** [comment]
Hello,

Ok, thanks for the information. That's basically what I am using too. Can you try with another web browser like Chrome ?

**Comment by hemantkamalakar** [comment]
Hello Marco,
The issue is now resolved with a setting on my router.
I was unable to access or ping other networked devices connected to my DLink router nor other devices can ping my laptop. The internet works perfectly from all the devices. Only issue is they can't communicate each other. The issue has been isolated to D-Link router setup. 
The fix is to disable "Enable MultiAP Isolation" option. Go to router setup page --> Setup --> Wireless --> Wireless Basic and un-check the box "Enable MultiAP Isolation" and press "Apply" button. This fixed the problem immediately and I could ping all devices on the LAN. and I can now control my Arduino from any device in the network.

Thanks  a lot for your help.

**Comment by marcoschwartz** [comment]
Great! Closing this :)
