### ISSUE TITLE
Large memory consumption for Global Variables (Arduino Mega 2560 Rev3)

### ISSUE THREAD

**Issue by orion9009** [marcoschwartz/aREST#51]
Hi there, just to inform you.

i seen you have updated library for the UI fix but now it consumption too large memory space for global variable.  From previous version the aRest library only used below 30% of my mega global variables memory but now it consume near 90% of it.  

Looking forward for you aRest library fix. TQ

**Comment by marcoschwartz** [comment]
Hi, you're right, I updated the output buffer (too much apparently!) so the UI that I am working on works correctly.

What I will do right now is revert the buffer size to normal & only make it bigger if the UI library is used. Sounds good to you? Thanks for noticing!

**Comment by orion9009** [comment]
So it is dynamic buffer based on the usage.. sounds good to me.

I also have another question, as i know the current aRest custom functions limit i can create are 5 functions right..   Can I create more than 5 functions as i need to extend / create more functions for my Smart Home project in the future?

**Comment by marcoschwartz** [comment]
Great! I just committed the changes.

For your question, yes it's possible, for now you can just do this in the code:

#define NUMBER_VARIABLES 10
#define NUMBER_FUNCTIONS 10

However I should make it bigger by default for the Mega, what do you think?

**Comment by orion9009** [comment]
as long it doesn`t cause instability, it will be great.

**Comment by marcoschwartz** [comment]
Sure, shouldn't be a problem, I marked on the to-do list. I'll mark this issue as closed now.

**Comment by orion9009** [comment]
Thanks

**Comment by marcoschwartz** [comment]
That's done now :)

**Comment by orion9009** [comment]
thanks again..
