### ISSUE TITLE
Float decimals missing on rest.variable()

### ISSUE THREAD

**Issue by FTell92** [marcoschwartz/aREST#52]
Hi, 

I miss my decimals when i send my variable to the web. I only receive two decimals. How can i print all my 8 decimals on the web?

**Comment by marcoschwartz** [comment]
Hi,

Thanks for using the library. This 'issue' is basically built-in into the library for now I need to convert a float to a chain of characters. Do you really need 8 decimals for your application? Thanks!

**Comment by marcoschwartz** [comment]
That's now done
