### ISSUE TITLE
WiFi_CC3000.ino, Example Resets itself and gets disconnected ?

### ISSUE THREAD

**Issue by sanjugem** [marcoschwartz/aREST#57]
WiFi_CC3000.ino always resets device , disconnect CC3000 and re-connects  after minutes . Expected was a long lasting stable connection . Since REST request can come any time .  I did not changed code but added some lines inside led handler function . Did any one had similar issue ?

**Comment by marcoschwartz** [comment]
That's basically due to the CC3000 itself, not the library. Did you try with the code from the example?

**Comment by marcoschwartz** [comment]
Closing this as it's related to the CC3000 chip.
