### ISSUE TITLE
ESP8266 timeout during upload.

### ISSUE THREAD

**Issue by roccomuso** [marcoschwartz/aREST#58]
Hi,

I can't upload the aREST.lua file and the init.lua to my esp8266 board due to timeout issue during the upload process (close to the 14% i get the error).

With other files it seems to work well o.o

Any suggestions?

**Comment by marcoschwartz** [comment]
Hi,

This repository is only for the Arduino-compatible aREST library. I answered about the LUA project on the other repo :)
