### ISSUE TITLE
Include consistent pin number in the repsonses

### ISSUE THREAD

**Issue by saliehendricks** [marcoschwartz/aREST#59]
1. When executing the api command /digital/2 the response is:
   { return_value: 0, id: "007", name: master_node", connected: true }

Please include:
{pin:2 return_value: 0, id: "007", name: master_node", connected: true }
1. When executing the api command /digital/2/1 the response is:
   {"message": "Pin D2 set to 0", "id": "007", "name": "master_node", "connected": true}

Please include pin 2 and return value 1:
{"pin": 2,"return_value": 1, "message": "Pin D2 set to 0", "id": "007", "name": "master_node", "connected": true}

This makes for loosely coupled request and response handling

(love this lib btw)

**Comment by marcoschwartz** [comment]
Thanks for the comment, marked this as a to-do :)

**Comment by Alfredynho** [comment]
thank you very much leaving know my question is this I want to use this in your arest library with an engine, but I want the engine by pressing a button start the engine , and rotate for five minutes and then stop ... and time management (delay) with your library

**Comment by marcoschwartz** [comment]
For delays, I recommend using a counter & if conditions instead of a delay() function that would block the behaviour of the library. See: http://playground.arduino.cc/Code/AvoidDelay
