### ISSUE TITLE
avr/wdt.h: No such file or directory

### ISSUE THREAD

**Issue by dipenpatel235** [marcoschwartz/aREST#61]
Can any one provide commented file?
o comment avr/wtd.h but not working...because i think many other line required to comment...

**Comment by marcoschwartz** [comment]
Hello, what board are you trying to use? Because the wdt.h file is included by default when you use a board that has the watchdog (for example the Arduino Uno)

**Comment by marcoschwartz** [comment]
Closing this as it's not related to aREST :)
