### ISSUE TITLE
Stray comma in "/" response output

### ISSUE THREAD

**Issue by jmealo** [marcoschwartz/aREST#63]
The response at the root endpoint ("/") contains a stray comma.

Actual output:
```
{"variables": {"blue_brightness": 0, "white_brightness": 0, "blue_target_brightness": 0, "white_target_brightness": 0}, 
```

**Comment by marcoschwartz** [comment]
Hi, thanks for reporting the bug. Can you tell me on which board/hardware combination it happened ? Thanks!
