### ISSUE TITLE
Connecting ESP8266 as SoftAP ( Access Point)

### ISSUE THREAD

**Issue by kitmaker** [marcoschwartz/aREST#64]
Hi , 
Please add some  Code , So that i could use ESP8266 as SoftAP ( Access Point ) Mode to Communicate with this library?

**Comment by marcoschwartz** [comment]
Hello! That's a nice suggestion indeed. What would you like to see exactly ? The library to be accessed within a WiFi network created by the ESP8266, or the possibility to initialize the ESP8266 as SoftAP & then make it connect to another WiFi network?

**Comment by kitmaker** [comment]
Hi!,
Thanks for the Fast Reply!
aRest is an Awesome Library and Perfect UI for any project...
& i would like to see - Library to be Accessed within a Wifi created by
Esp8266 (SoftAP Mode)

, there are many webpages for At Commands which initialize Esp8266 in
SoftAP Mode.

**Comment by kitmaker** [comment]
Hi,
Seeking for Fast Action .. Because i was making project on this Library
....
Please Reply if you could add 1 Wire Support too for DS18B20 Temperature
sensor ,
I think you could import code of nodeMcu for 1 wire? / SoftAP?

Thanks ,
Ayush

**Comment by marcoschwartz** [comment]
About the 1 Wire support, I always refused to include specific support for sensors into the aREST API, as this is too specific. To integrate sensor readings, simply create an aREST variable & then store the readings from the sensor in that.

**Comment by kitmaker** [comment]
I am Ok without 1Wire , so no worry about it.

Just let me know if you got any key to SoftAP . ?

**Comment by marcoschwartz** [comment]
Sure, I'd just need some time to implement it :) Once it's done I'll release it as an example in the library folder.

**Comment by kitmaker** [comment]
Thanks man !
Do notify me , when done!

**Comment by kitmaker** [comment]
Any Progress?

**Comment by marcoschwartz** [comment]
Example tested & uploaded! Let me know if it works for you, then I'll close this.

**Comment by kitmaker** [comment]
Thanks for your Effort !
Sure, i will test it within 5 days because my esp8266 is in transit.
And 1 Question : I have uploaded the esp8266 library in arduino , so should
i choose "generic esp8266"?

**Comment by marcoschwartz** [comment]
You're welcome. Well you need to choose whatever board you have, there are a lot of choices now in the library.

**Comment by kitmaker** [comment]
Mine is Esp-02 , it dosen't have any Board Named Esp-02 So I think i will
choose generic esp8266?

**Comment by marcoschwartz** [comment]
Yes, in that case you need to choose the Generic option.

**Comment by marcoschwartz** [comment]
That seems like warnings only to me, I got it too. Are you sure it doesn't work ?

**Comment by kitmaker** [comment]
Not tried yet , i will try it on esp-01 in 3 days which i have bought now.
Could you try it on your esp-12 ??
Looks like arestUI is not compatible with SoftAP?

**Comment by zasf** [comment]
Hello,

SoftAP works fine :) thanks for this useful library!

How do I change the ssid & password in SoftAP mode?

I'm using ESP8266_softAP sketch, but WiFi.softAP(ssid, password) doesn't change ESP8266 ssid

Thanks

**Comment by kitmaker** [comment]
Hi,
Have you tried with arestUI library too?

**Comment by zasf** [comment]
No, I haven't tested the UI library, as I don't plan to use it. I'd like to send commands with Android devices, can you suggest any apps?

**Comment by zasf** [comment]
In order to change ssid & password, password needs to be at least 8 characters long

    // WiFi parameters
    const char* ssid = "testtest";
    const char* password = "testtest"; // at least 8 characters
    ...
    WiFi.softAP(ssid, password)

**Comment by kitmaker** [comment]
Hi,
Could you Try my Code Above , which uses ArestUi too.
I don't have esp8266 Available now.
So , i Hope you could test it.
It gives some errors but still would Compile.

**Comment by zasf** [comment]
![schermata 2015-09-05 alle 10 13 14](https://cloud.githubusercontent.com/assets/6288220/9698442/d6c058d8-53b6-11e5-95c0-e670bfed4d8e.png)

The code compiles and uploads fine. On my ESP-01 it is rather slow though, from a very quick look it doesn't seem to be suitable for serving html pages.

**Comment by kitmaker** [comment]
Hi,
Very Thanks for Testing!
Could you tell me that how could i move the labels ?

**Comment by kitmaker** [comment]
Brother, how did you programmed your esp-01?
I get "
AT

Error
"
When i Type AT
Could i know your Connections with Esp-01 for programing?

**Comment by kitmaker** [comment]
After all made it to Work!
But  it is slow like a snail :(
How could i speed it up?

**Comment by marcoschwartz** [comment]
Does everybody only have speed problems using the SoftAP sketch? I never had problems using aREST UI when connecting to a WiFi router.

**Comment by kitmaker** [comment]
Yup there is a serious problem, sometimes it loads and sometimes not.

**Comment by marcoschwartz** [comment]
About aREST UI + SoftAP, it definitely makes sense: aREST UI doesn't work without the web as it uses jQuery & Bootstrap. As a SoftAP, the ESP doesn't have access to the Internet, so that's why the UI doesn't work correctly.

**Comment by kitmaker** [comment]
Could it be solved?

**Comment by marcoschwartz** [comment]
As I don't see a way to embed jQuery, unfortunately no, or it's outside of my domain of competence. If somebody has an idea, I am listening :)

**Comment by kitmaker** [comment]
No Problem ! , I got my SoftAP Working & I would be closing this issue.
