### ISSUE TITLE
How to set variable

### ISSUE THREAD

**Issue by devrosx** [marcoschwartz/aREST#66]
Hello, 
aREST works great, and i can without problems read variables from Arduino with JS page. But what if want send variable value to arduino. Some function like .setVariable? I want to use slider to change variable with time in arduino.

 Thanks...

**Comment by marcoschwartz** [comment]
Hello, I definitely agree that there should be a way to do that. To be completely RESTful, this would need to be done via a PUT call. 

However, for now I only used GET calls for aREST so devices can be controlled directly from a browser. So I might simply implement something like:

http://arduino.local/temperature?value=25

What do you think ?

**Comment by DontBelieveTheByte** [comment]
I think it's an awesome idea but I much rather wait and see proper PUT calls then improper GET requests.

**Comment by bartekkam** [comment]
Hello,

I've read your tutorial about aREST and CC3000 on Adafruit and got confused about this part:

>The other feature from the API that you can use is the ability to define your own functions, so they can be called directly from a REST call. Imagine for example the case where you want to execute a sequence of command: it is much more efficient to encapsulate all these commands in a single function, instead of making several REST calls. Note that all functions must return an integer type, and take a String as the unique argument, which will contain the different parameters for the function. You can see for example the function defined in the example:
```
int ledControl(String command) {
  
  >// Get state from command
  int state = command.toInt();
  
 > digitalWrite(7,state);
  >return 1;
}
```
>Just as the variables, the functions have to be declared with an alias so they can be called by the API:
```
>rest.function("led",ledControl);
```
The function can then be called by the REST API in your browser, using the name of the alias followed by the parameters:

>http://arduino.local/led?params=1

>Once you sent this REST call, you should have the confirmation that the function has been executed:

>Function led has been executed

According to this it is possible to change variable's value on Arduino using aREST by passing it as string in function argument. Do I understand correctly?

**Comment by marcoschwartz** [comment]
Indeed, for now the only way to change the value of a variable from the outside is to use a function like you described it.

**Comment by WilkoV** [comment]
Hello,

any news on this topic. I would realy like to see post/put/delete actions.

Thx

**Comment by marcoschwartz** [comment]
Not yet released, but I am implementing it on boards that will have enough memory space for such advanced functions, like the ESP8266, MKR1000, etc. :)

**Comment by rbailets** [comment]
I'm uncertain as to what this simple function is doing, and how it might be called as a serial command.
when this request is sent - http://arduino.local/led?params=1
   does this line of code:
       `int state = command.toInt();`
   convert the param string 1 into an integer
   and in the next line 
      `digitalWrite(7,state);`
   set pin 7 to high (in this case since params=1)

If this is correct. How would the function be called as a serial command?
      `/led/1`
      `/led/params/1`
      `/led?params=1`

Can you, and how would you multiple parameters?

**Comment by OidaTiftla** [comment]
May you find this useful. I also looked for a way to get the whole url in my function and also return more than just one 'int' return value. I only tested it on my arduino and I also did not look to much for saving resources. It works for my use-case and I did not document the functionality in the README, sorry for that. But it was just a small solution to solve my use-case.

I added something similar to the functions and called it controllers. The functions you can register as a controller must have a signature like this: ```void myController(Buffer<OUTPUT_BUFFER_SIZE> & out_buffer, String &url)```

Here is an example:
```
void setup() {
    // Function to be exposed
    rest.controller("temperatures", temperaturesController);

    // add some other setup stuff
}

void temperaturesController(Buffer<OUTPUT_BUFFER_SIZE> &out_buffer, String &command) {
    // do some stuff
    // I used it to interface the OneWire bus

    DeviceAddress device;

    out_buffer.add(F("{"));
    // check format of command
    if (command == F("/temperatures")
        || command == F("/temperatures/")) {
        // return all id's
        sensors.begin();
        out_buffer.add(F("\"sensor-ids\": ["));
        bool removeCommaSpace = false;
        auto count = sensors.getDeviceCount();
        for (uint32_t i = 0; i < count; ++i) {
            sensors.getAddress(device, i);
            out_buffer.add(F("\""));
            for (uint8_t *p = device; p != device + 8; ++p) {
                auto hexString = String(*p, HEX);
                if (hexString.length() < 2) {
                    out_buffer.add(F("0"));
                }
                out_buffer.add(hexString);
                out_buffer.add(F(":"));
            }
            out_buffer.removeLastChar();
            out_buffer.add(F("\", "));
            removeCommaSpace = true;
        }
        if (removeCommaSpace) {
            out_buffer.removeLastChar();
            out_buffer.removeLastChar();
        }
        out_buffer.add(F("], "));
    } else if (command.startsWith(F("/temperatures/"))) {
        command = command.substring(14); // 14 = length of "/temperatures/"

        if (command.indexOf(':') >= 0) {
            // read by address
            for (uint8_t i = 0; i < 8; ++i) {
                auto start = command.begin() + 3 * i;
                auto value = (uint8_t) strtol(start, 0, 16);
                device[i] = value;
            }
        } else {
            // read by index
            // retrieve device address
            auto index = (uint8_t) strtol(command.begin(), 0, 0);
            sensors.getAddress(device, index);
        }
        // configure to wait for conversion completed
        sensors.setWaitForConversion(true);
        sensors.setCheckForConversion(false);
        // call sensors.requestTemperatures() to issue a global temperature
        // request to all devices on the bus
        sensors.requestTemperaturesByAddress(device);

        delay(10);

        // read temperature
        auto tempC = sensors.getTempC(device);

        // Send feedback to client
        if (tempC == DEVICE_DISCONNECTED_C) {
            out_buffer.add(F("\"message\": \"Device is disconnected.\", "));
        } else {
            out_buffer.add(F("\"temperature_Celsius\": "));
            out_buffer.add(tempC);
            out_buffer.add(F(", "));
        }
        out_buffer.add(F("\"sensor-id\": \""));
        for (uint8_t *p = device; p != device + 8; ++p) {
            auto hexString = String(*p, HEX);
            if (hexString.length() < 2) {
                out_buffer.add(F("0"));
            }
            out_buffer.add(hexString);
            out_buffer.add(F(":"));
        }
        out_buffer.removeLastChar();
        out_buffer.add(F("\", "));
    } else {
        out_buffer.add(F("\"message\": \"Unknown command '"));
        out_buffer.add(command);
        out_buffer.add(F("'.\", "));
    }
    out_buffer.add(F("\"id\": \""));
    out_buffer.add(ID_REST);
    out_buffer.add(F("\", \"name\": \""));
    out_buffer.add(NAME_REST);
    out_buffer.add(F("\", \"hardware\": \""));
    out_buffer.add(HARDWARE);
    out_buffer.add(F("\", \"connected\": true}"));
}
```
If you would like to get an overview of the implementation of the controllers you may look on this commit: e3599482046dc77b866051ec4006b0576a7adfbc

If there are any further questions, may I can answer them.

**Comment by marcoschwartz** [comment]
Hi, the issue is that it's very hard to do without breaking the compatibility with some old Arduino boards that can't handle all the extra code required for that. I am still thinking about how to do that the proper way, if someone has suggestions I'd be happy to look at any pull requests :)

**Comment by maheraldous** [comment]
Any other ways to change the value of the variables?

I like the API and I hope if the Arduino have it in it's core.

What I want is to make a small lock that close and open with random code, that's way I want to change the variable with API.
