### ISSUE TITLE
When calling /digital/0/1 before /mode/0/o aREST gives no error message

### ISSUE THREAD

**Issue by zasf** [marcoschwartz/aREST#68]
If you call `/digital/0/1` without setting before `/mode/0/o`, aREST will say:

```
{"message": "Pin D0 set to 1", "id": "1", "name": "esp8266", "connected": true}
```

but GPIO0 is not actually high. 

aREST should either:
1. point out that GPIO0 is not in output mode
2. turn GPIO0 in output mode and then set it HIGH

I'm not sure what is the correct behavior. At the moment aREST behavior is confusing because after sending `/digital/0/1` you would expect GPIO0 to be high but instead GPIO0 is low and you get a "Pin D0 set to 1" message

**Comment by marcoschwartz** [comment]
That's a good point, I'll mark that as a bug & enhancement request. I think indeed the message should be changed. The goal of the /digital/0/1 command is really to make the digitalWrite() operation, and nothing else.

**Comment by pickeld** [comment]
is it possible to skip the mode command? or to set it by default withing the Arduino IDE sketch?

thank you.

**Comment by marcoschwartz** [comment]
Sure, you can perfectly 'hard encode' it into the Arduino code as well.
