### ISSUE TITLE
Newbie 

### ISSUE THREAD

**Issue by steinacoz** [marcoschwartz/aREST#70]
Having gone through your book. I am new to arduino and esp8266 and I want to read sensor values to Android Android phone from arduino uno using esp8266 (independent) and your aRest library. Is it possible and can you give me and can you please give me a head way. Thanks

**Comment by marcoschwartz** [comment]
Hello, sure that's possible. If you want to use it right away, you can simply use the same web commands from aREST from your phone browser. If you want a graphical interface, you can for example develop an android app that will do the same. Also check this app made by one of my readers: https://play.google.com/apps/testing/org.zetaremote

**Comment by zasf** [comment]
Hello, I'm the author of the app Marco was referring to. Can you elaborate on what you want to do? My app can be used to send commands but not yet to receive values. Anyway it is still a work in progress and return values can be added.
