### ISSUE TITLE
Randomly reset ESP8266, cause:2, cause:4

### ISSUE THREAD

**Issue by mathzol** [marcoschwartz/aREST#72]
While asking the rest server, (I used the example code), it randomly reset and said that via console:

```
Exception (0):
epc1=0x401003d6 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3ffeaee0 end: 3ffeb110 offset: 01a0

>>>stack>>>
3ffeb080:  3ffe9444 00000000 3ffe9478 4020726c  
3ffeb090:  3ffe8d60 00000000 3ffeb0b0 402045c8  
3ffeb0a0:  3ffe9444 00000000 3ffeb134 402025b9  
3ffeb0b0:  3ffe8be8 00000000 000003e8 40206b8c  
3ffeb0c0:  00000000 00000000 3fff58f0 00000159  
3ffeb0d0:  00000000 00000000 00000016 40101b11  
3ffeb0e0:  40201ff9 8b01a8c0 00000000 3ffeb13c  
3ffeb0f0:  3fffdc20 00000000 3ffeb134 40202056  
3ffeb100:  00000000 00000000 3ffea0f0 40100378  
<<<stack<<<
 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
```

Any idea what was happening?

**Comment by marcoschwartz** [comment]
Hey Mathzol! Is that happening after a given number of request to the aREST server, or sometimes also from the start ?

**Comment by mathzol** [comment]
Sometimes also from the start. Totally randomly did it.

**Comment by marcoschwartz** [comment]
That's strange, and definitely not the memory leak issue I could think about. Which board are you using?

**Comment by mathzol** [comment]
I think ESP8266 12 or 12E. 

http://www.ebay.com/itm/400923947498?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

**Comment by rajbadri** [comment]
same here random resets using esp8266-12 and esp8266-12e

**Comment by marcoschwartz** [comment]
Marking this as a bug, I'll investigate this issue with my own esp-12

**Comment by mathzol** [comment]
Okay, thanks. If I can help by somehow, just feel free to ask for. I have a Saleae, some debug stuffs, don't know how I start. Is it a hardware difference issue, or something with the software?

**Comment by Jorgen-VikingGod** [comment]
I think this is about the callback / interrupts of the pubsubclient.
Have same errors on my settings - totally random resets.
But as I can see, the resets came really often if you have many fast mqtt messages handled...
