### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by wmarchewka** [marcoschwartz/aREST#77]
Im trying to learn more about your awesome restful server and mqtt.  I am trying to use the debug to output to serial, but nothing seems to work. The only output i am getting is "Wifi connected" and "Attempting MQTT connection...."

I tried #define DEBUG_MODE 1 in the ESP8266_cloud.ino as well as aRest.H.

Also i do not see where the #define statement is to select the ESP8266.

Thanks. Sorry to open an issue for this.

**Comment by marcoschwartz** [comment]
Hello Walter, no problem! Can you tell me which #ID you are using for your device? Then I can check on the server in live if it connected or not.

**Comment by wmarchewka** [comment]
47FDD9

**Comment by marcoschwartz** [comment]
From what I see on the server your device is connected ... can you try to access it via cloud.arest.io ?

**Comment by wmarchewka** [comment]
i can toggle the values through the cloud based. but i am trying to have more output from debug to learn the workings .
