### ISSUE TITLE
there is not enough space

### ISSUE THREAD

**Issue by siyangYao** [marcoschwartz/aREST#78]
After import aREST, I want to run the code on arduino. It always shows "there is not enough space"

**Comment by marcoschwartz** [comment]
Hello, I would need to know a bit more in order to help you, like:

- which hardware do you use ? (UNO, etc)
- which Arduino IDE do you use?
- which connectivity do you use (CC3000, etc)

Thanks!

**Comment by Shipow** [comment]
I'm running on Uno with CC3000 (lib from adafruit) and I experience the same kind of issue.

**Comment by marcoschwartz** [comment]
At least the aREST + CC3000 example sketch still compiles fine on my side. Are you using a custom sketch that produces this issue?
