### ISSUE TITLE
Custom functions not receiving params on ESP8266 Cloud Access

### ISSUE THREAD

**Issue by tomasmcm** [marcoschwartz/aREST#79]
Using the same function below on examples `ESP8266.ino` and `ESP8266_cloud.ino` results in different outputs.

```
//inside setup()
rest.function("print", printHandler);

//custom function
int printHandler(String command) {
  Serial.println("Message received:");
  Serial.println(command);
  return 0;
}
```

With the local version the command is printed to the console. With the Cloud Access version the command is not printed.

**Comment by marcoschwartz** [comment]
Indeed, functions are not yet supported on the cloud access :) Marking this a feature request

**Comment by tomasmcm** [comment]
Thanks :D 
So currently there is no way to send data TO the ESP8266, only FROM the ESP8266 via cloud access?

**Comment by marcoschwartz** [comment]
Data ... well you can certainly control pins, but not yet set the value of variable using a function, indeed. I'll make sure to include functions in the cloud access soon, should not be too difficult.

**Comment by marcoschwartz** [comment]
That's now fixed :)
