### ISSUE TITLE
esp8266/esp12e stops responding after a first successful call

### ISSUE THREAD

**Issue by aperepel** [marcoschwartz/aREST#80]
Hi, I'm following a basic https://github.com/marcoschwartz/aREST/blob/master/examples/ESP8266_softAP/ESP8266_softAP.ino example.

* Upload the program fine, it starts an AP and reports an IP
* Connect Android phone to this AP
* Issue e.g. a request to a root to dump all variables, etc.
* First call returns fine, but subsequent invocation never returns

Here's DEBUG output from the esp8266:
```
Request received
GET /
 HTTP/
Sending command
Command: r
State: x
State of buffer at the start:
Added to buffer: temperature
Added to buffer: 24
Added to buffer: humidity
Added to buffer: 40
Added to buffer: 1
Added to buffer: esp8266
State of buffer at the end: HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS
Content-Type: application/json
Connection: close

{"variables": {"temperature": 24, "humidity": 40}, "id": "1", "name": "esp8266", "connected": true}

Buffer size: 258
```

**Comment by aperepel** [comment]
I have modified the example to connect to my WiFi AP instead of ESP8266 serving as one, and things work as expected. Something is going on with the ESP8266 AP mode example, but I'm not proficient in C++ yet to debug buffer flushes, etc (I'm a Java guy by trade :)

**Comment by marcoschwartz** [comment]
In that case it seems more like an issue with the ESP8266 library than aREST :) Closing this one
