### ISSUE TITLE
Mode command returns invalid JSON

### ISSUE THREAD

**Issue by aperepel** [marcoschwartz/aREST#81]
```
12:37:40::first ♨ >  curl -s http://192.168.1.167/mode/1/0 | jq .
parse error: Invalid numeric literal at line 1, column 23
12:38:02::first ♨ >  curl -s http://192.168.1.167/mode/1/0
{"message": "Pin D1"id": "1", "name": "esp8266", "connected": true}
```

Note how Pin D1 has an extraneous quote.

**Comment by marcoschwartz** [comment]
Can you tell me more about the hardware you are using? Thanks!

**Comment by CyanoFresh** [comment]
Same response

**Comment by PKGeorgiev** [comment]
aREST returns invalid json string when you supply incomplete/wrong or no arguments to one of the reserved keywords like mode, analog, digital no mater what hardware you are using . You can test it with Serial example:
1) Compile and upload Serial.ino;
2) Open Serial monitor
3) Type "mode" (without quotes). The result is: 
{"message": "Pin D0"id": "2", "name": "serial", "hardware": "arduino", "connected": true}

4) Type "digital". The result is:
"id": "2", "name": "serial", "hardware": "arduino", "connected": true}

5) Type "analog". The result is:
"id": "2", "name": "serial", "hardware": "arduino", "connected": true}

**Comment by marcoschwartz** [comment]
@PKGeorgiev Indeed, definitely something I need to fix by including a default message when the entered command is invalid.
