### ISSUE TITLE
Allow ESP8266 to work with both cloud.arest.io as well as local network req/resp

### ISSUE THREAD

**Issue by saliehendricks** [marcoschwartz/aREST#86]
It would be great if capable devices are able to respond to both cloud.arest.io requests as well as local network requests.

I tried creating a new instance to manage local requests alongside the cloud instance:

``` c
WiFiClient espClient;
PubSubClient client(espClient);

// Create aREST instances
aREST cloudRest= aREST(client);
aRest localRest = new aRest(), 
```

then in the loop()

``` c
//localRest.handle(espClient); doesnt work here either
cloudRest.loop();
while(there is a network){
  localRest.handle(espClient);
}
```

Ran into issues with this. May be a memory issue since i dont think this is intended operation. Also something that could be problematic is that I have a list of 6 variable Strings that I assign to both instances (although I thought these are just references being passed in).

**Comment by marcoschwartz** [comment]
Interesting, this is something I never tried as well. What were the issues exactly ?

**Comment by marcoschwartz** [comment]
This is now implemented and included in the examples of the library.
