### ISSUE TITLE
set mode from sketch

### ISSUE THREAD

**Issue by pickeld** [marcoschwartz/aREST#88]
Hello.
first i want to say you did really great job here! keep on!

Every time i unplug my esp8266 for a power source and re-plug it, i need to set the mode.
(http://192.168.1.9/mode/2/o)

is it possible to set the mode right from the Arduino IDE sketch?
so i wont need to set it again and again?

thank you!

**Comment by saliehendricks** [comment]
@pickeld I normally just loop through the pins and set the mode in the function setup()

```c
int relayPins[] = {5,1,3};
int relayCount = 3;
...
setup() {
  for (int i = 0; i < relayCount; i++)
  {
    pinMode(relayPins[i],OUTPUT);
  }
```

**Comment by pickeld** [comment]
thank you saliehendricks. you solved my issue
