### ISSUE TITLE
Arest cloud - callback function payload

### ISSUE THREAD

**Issue by brinuk** [marcoschwartz/aREST#90]
Sorry to open this as an issue,  it is more a plea for help. 
I am using your excellent arest cloud library,  for which I would like to offer my thanks. 
In my application I am trying to print the "byte* payload"  variable in the callback function and use the data in my application.  Unfortunately I am relatively new to all variants of the C language and having spent some time on this attempt I am now at a loss.
I should be very grateful if you had a little time to explain how I might read the contents of "payload", preferably to print the contents with something like Serial.print
Thank you
Brian Lambert

**Comment by marcoschwartz** [comment]
Hi Brian, thanks! Well what I could do is to print the content of the payload as the standard debug output of aREST, would that help?

**Comment by brinuk** [comment]
Thank you for your prompt reply. 
Perhaps if I indicate what I am trying to achieve. 
I have connected an Arduino Uno to an ESP8266 - 01 via tx and rx pins. The esp8266 is running your arest cloud sketch. I can pass values for temperature and humidity from Arduino to esp8266 and so to my dashboard.arest.io. However I need to read the contents of byte* payload in order to pass the appropriate  actions  to the Arduino.  To do so I need firstly to print the contents of payload so I may decide how to act on it's contents. 
As you will have guessed,  I am very new to all this. So I don't know if your suggestion will enable me to achieve the above. 
Thank you once again for your kind assistance. 
Regards Brian

**Comment by brinuk** [comment]
Your last reply regarding debug output was sufficient to direct me to the area in your aRest.h file that, with a small modification, has supplied the data that I was looking for.
Thank you for all your help.
Regards Brian

**Comment by marcoschwartz** [comment]
You're welcome!
