### ISSUE TITLE
Question: string variables only supported by Arduino Mega and ESP8266.

### ISSUE THREAD

**Issue by nerdyscout** [marcoschwartz/aREST#93]
Hi,

in your short manual you write:
> Variables
> You can also directly call variables that are defined in your sketch. Integer variables are supported by the library. Float and String variables are also supported, but only by the Arduino Mega board & by the ESP8266.

currently I'm trying to port your great lib into my project using a 328p microprocessor. Unfortunately I need string variables as well. Could you maybe briefly describe why this is only supported by these processors? The only thing I could imagine is insufficient program memory.
Maybe you also got me a hint to hack around this issue.

**Comment by marcoschwartz** [comment]
Hello, indeed it's a memory issue. However Strings should work fine if you are not using the CC3000 library, which is the biggest memory-eating component. Do you get a compile error when using strings?

**Comment by nerdyscout** [comment]
Hello Marco,
thanks for your support! Currently, as workarround, I diactivated the preprocessor commands according string variables so they can be used. This is working fine, even with the CC3000 lib. As my code size is currently ~ 97% of the 328p I have to change the processor anyway...

From my point of view this issue is closed.
