### ISSUE TITLE
JSON return values not enclosed in quotes

### ISSUE THREAD

**Issue by shanetoven** [marcoschwartz/aREST#94]
When executing a query for values, the returned JSON does not enclose certain values in quotes. This includes the actual "return_value" as well as "connected". The lack of quotes causes blank values with sites using JSON to query data for collection and display.

Incorrect...
{"return_value": 1023, "id": "testdevice", "name": "Lab", "connected": true}

Correct...
{"return_value": "1023", "id": "sds001", "name": "Lab", "connected": "true"}

**Comment by PKGeorgiev** [comment]
@shanetoven  I disagree on that! "1023" is of type string and 1023 if of type int. As well true is bool, but "true" is a string. What you want to do is to convert everything to type string. This is wrong. It is responsibility of JSON clients to correctly parse json strings. Also blank values are not allowed - http://www.json.org.
If this lib returns blank values - it is another bug. You should not workaround "blank" values converting them to empty strings.

**Comment by shanetoven** [comment]
I wasn't the one who suggested that--and I'm not terribly familiar with JSON structures. Just glad there is a workaround.

--
Shane Toven
shanetoven@gmail.com

    _____________________________

**Comment by marcoschwartz** [comment]
Closing this for now as indeed the library returns correct values :) Check http://jsonlint.com/
