### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yomasa** [marcoschwartz/aREST#96]
Can anybody point me to an example the HTML form that post to a device using aREST ?

Thanks

**Comment by marcoschwartz** [comment]
Hi! If you are willing to use a bit of JavaScript I recommend using the aREST.js project https://github.com/marcoschwartz/aREST.js

From there you'll be able to control aREST boards using HTML forms :)

**Comment by yomasa** [comment]
Thank you for that!,  So heres what I am finding out, every time I send a rest call to the esp8266 the Free heap gets smaller, if you let it sit for a while the memory starts coming back, So the example you give in aRest.js with the timer will kill all the free heap if you let it run for a while.  What do you think is going on?

**Comment by yomasa** [comment]
Can you have a function the that returns more then one value? If so what the syntax?

I would like to return this as a json

long devices[6][7] ={
  {8067417,11132936,11132934,4,306,delay4,0}, // Living Room
  {2045033,11132930,11132929,4,306,delay4,0}, // Bed Room
  {13121881,11132941,11132931,4,306,delay4,0}, // Kitchen
  {6623641,5584131,5584140,4,182,delay4,0}, // front pir - washer light
  {6623641,5577987,5577996,4,182,delay8,0}, // front pir - backyard light
  {8409129,11132936,11132934,4,305,delay4,0} // front door Sensor - live light
};

Thanks
Jorge

**Comment by kiralikbeyin** [comment]
Hi,
I am also trying to get or set more values from a variable like 
/myvar

 {"myvar": "value1", "value2", "value3"}

nested arrays and nested objects we need...

@yomasa are you working locally or cloud or both? If you made both can you share your code?

**Comment by yomasa** [comment]
I am working remotely but with my own code not using mqtt, using rest commands.  I decided against mqtt awhile ago.  Just one extra piece to maintain and not needed for my project.  I have a fear of the cloud and it's lack of reliability.

**Comment by yomasa** [comment]
@marcoschwartz 

The aRest.js works great!  I have compiled it with phonegap and get no errors, It runs on my phone seems like the ajax is not working, When I type in the ip and hit validate nothing happens, not getting or sending any data.

Have you done this yet?

**Comment by marcoschwartz** [comment]
Not something I've done yet, but something I definitely have in my plans :)
