### ISSUE TITLE
Wemos D1 and Pinout

### ISSUE THREAD

**Issue by jayraydee** [marcoschwartz/aREST#98]
Hey guys! awesome work, just trying to set this up on my wemos D1 R2 board, got it working via web browser via the could.arest.io and by IP address. but here's the catch, I still cannot control the Led via D1-D8. I know the led is set up right because if i plug it in D4 it lights up, (still not controllable).

Anyone seen this sort of thing before? Is it a issue with the board?

**Comment by marcoschwartz** [comment]
Thanks! I must admit I never tried it with this board, only with the ESP8266 chip alone. However I am not sure I understand the problem, you can't control outputs with aREST?

**Comment by jayraydee** [comment]
That is correct, I cannot control the outputs. Software wise it's responding to the commands I send it and I can define all the pins as outputs (cloud.arest.io/wemos/mode/5/o),

and toggle them from high to low(cloud.arest.io/wemos/digital/5/1), and the browser shows the response is happening correctly. 


But hardware wise, nothing happens with the digital output pins.

**Comment by marcoschwartz** [comment]
I see. Next step would be to enable the debug mode and let me know what happens. Can you put this in your sketch:

#define DEBUG_MODE 1

Then, send a few digital write commands, and post the output of the Serial monitor here :)

**Comment by jayraydee** [comment]
okay!

Here's the input/output
*ESP8226_Cloud:*
...
WiFi connected
Attempting MQTT connection...Connected to aREST.io

Was able to connect via cloud.arest.io, which worked, but no response on
the serial monitor.

*ESP8266_softAP:*
...
WiFi connected
Attempting MQTT connection...Connected to aREST.io

Then used the cloud.arest.io to send it comands, which worked, but no
responses on the serial monitior.

*Wifi:*

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1264, room 16
tail 0
chksum 0x42
csum 0x42
~ld

This looped endlessly and was unaccessible via cloud.arest.io


Anything else you would suggest to test?

**Comment by jayraydee** [comment]
I just tested the ESP8266_cloud with a NodeMCU v 0.1 board I have on hand,
and the same problem is happening. I can talk to the board via the cloud,
but nothing happens to the LED on the digital output pins. What if im doing
something else wrong?

**Comment by marcoschwartz** [comment]
Do you also get the wdt reset error using the NodeMCU board ?

**Comment by jayraydee** [comment]
I don't think so, is that an error on the serial monitor or the web page?

**Comment by marcoschwartz** [comment]
On the serial monitor, just like the one you had:

wdt reset
load 0x4010f000, len 1264, room 16
tail 0
chksum 0x42
csum 0x42
~ld

**Comment by jayraydee** [comment]
Okay, here's what I got when I used the NodeMCU board, I was able to talk to it but still no luck controlling the LED I have connected on D2. FYI, I tested the led set up and its working fine.

WiFi connected
Attempting MQTT connection...Connected to aREST.io
//command sent: https://cloud.arest.io/wemos/mode/2/o
Memory loss before reset:4294925480
Memory loss after reset:0
Memory free:41816
//command sent: https://cloud.arest.io/wemos/digital/2/1
Memory loss before reset:0
Memory loss after reset:0
Memory free:41816
//command sent: https://cloud.arest.io/wemos/digital/2/0
Memory loss before reset:0
Memory loss after reset:0
Memory free:41816
//command sent: https://cloud.arest.io/wemos/digital/2/1
Memory loss before reset:128
Memory loss after reset:0
Memory free:41688

So it looks like we are able to talk to the board but not actually digitally write to the pins of the board. Any theories on what is causing the disjunction?

Just for better troubleshooting, here's the product that I'm using:
[V3 4M bytes (32Mbits) FLASH NodeMcu Lua WIFI Networking development board Based ESP8266 with firmware-in Other Electronic Components from Electronic Components & Supplies on Aliexpress.pdf](https://github.com/marcoschwartz/aREST/files/211592/V3.4M.bytes.32Mbits.FLASH.NodeMcu.Lua.WIFI.Networking.development.board.Based.ESP8266.with.firmware-in.Other.Electronic.Components.from.Electronic.Components.Supplies.on.Aliexpress.pdf)

**Comment by marcoschwartz** [comment]
Really strange ... the code is using the standard Arduino digitalWrite() function, so I can't see what can be the problem here :( If anybody else reading this has this board as well, would be great to test aREST on it as well!

**Comment by marcoschwartz** [comment]
I just tested with a D1 Mini, it actually works very well :) The 'problem' is that the pinouts are different on the board compared to the Arduino pins, see: http://www.wemos.cc/Products/d1_mini.html

**Comment by tstauch** [comment]
@marcoschwartz I look forward to trying the D1 with AppShed IoT.... 
Am I correct in understanding that the pinouts will match the standard NodeMCU, and will work fine with aREST?

**Comment by marcoschwartz** [comment]
Yes indeed, i will automatically do the pin conversions now :)
